### ISSUE TITLE
Downloadable Sony apps?

### ISSUE THREAD

**Issue by tommiehansen** [ma1co/Sony-PMCA-RE#1]
Could you upload Sony apps or are they under some copyright law? I don't seem to be able to download apps via your homepage; probably because it was forever since i actually downloaded any Sony apps.

And have you had time to make any sense of how the apps work?

**Comment by ma1co** [comment]
The market downloader seems to be a bit buggy, sometimes it works, sometimes it doesn't. Play with the pmca.marketclient source if you want to try yourself...

I'm currently trying to understand the functionality provided by the android subsystem. Refer to this project: [PMCADemo](https://github.com/ma1co/PMCADemo)
