### ISSUE TITLE
Unable to hack ilce-7

### ISSUE THREAD

**Issue by pippo73** [ma1co/Sony-PMCA-RE#10]
Hi, 
I'm trying to install your hack but there is no way to make it work :(
This are the messages I get.
```
Loading plugin
Plugin loaded
Starting task
Got task key
Cancelling plugin
Plugin cancelled
Starting download to camera
Progress: Uploading 0%
Device error: SSL
```
While the camera remains in "application download" mode.

How can I help to debug the problem.

System window10 - ILCE7 - fw ver 3.10

**Comment by pippo73** [comment]
Some update...
The web update does not work, but the command line hack worked and I was able to install youw APK.
Thank you very much!!! :)

**Comment by ma1co** [comment]
Set your clock's time and date and disable your antivirus. I'll close the issue since you got it to work.

**Comment by pippo73** [comment]
What do you mean with "Set your clock's time and date"? where, I have them both on set on pc and camera.

**Comment by ma1co** [comment]
Camera's time i meant. Well, then it is probably some kind of antivirus. The official Sony app store will most likely not work either.

**Comment by rigrx** [comment]
@ma1co Do you know if this hack works with the new firmware update 3.20 too? :)

**Comment by pippo73** [comment]
@rigrx 3.20? the last one is not 3.10? where did you found it?

**Comment by rigrx** [comment]
@pippo73 there was a update on 26.04.2016 - [here ](https://esupport.sony.com/US/p/swu-download.pl?mdl=ILCE7RM2&upd_id=10761&os_group_id=29) to go :)

**Comment by pippo73** [comment]
Here is the reason... you are talking about the mark2, I'm a poor guy with a mark1 :D

**Comment by rigrx** [comment]
@pippo73 Ups haha :D Well, I get my a7R II in 3 hours. Hope that @ma1co will reply soon..

**Comment by ma1co** [comment]
@rigrx Yes, it should work with fw 3.20.
