### ISSUE TITLE
Cant install on a6500

### ISSUE THREAD

**Issue by quallsb72** [ma1co/Sony-PMCA-RE#102]
usb.core.USBError Erno13 Acess denied (insufficient permissions)

**Comment by cassera88** [comment]
i keep getting same error. Have you found any solutions. Mine camera is 7R2

**Comment by lapol** [comment]
Try on different computer with Windows. Had the same problem on my Mac.

**Comment by ma1co** [comment]
Duplicate of #41. Please see my comment there.
