### ISSUE TITLE
Always getting this error when i try to view camera details

### ISSUE THREAD

**Issue by cassera88** [ma1co/Sony-PMCA-RE#103]
usb.core.USBError Erno13 Acess denied (insufficient permissions) when trying to view camera information or downloading the app

**Comment by benborman** [comment]
I am also having this issue! @ma1co any insight? Seems to be several people experiencing this. Thanks!

**Comment by polynar** [comment]
I am also having this issue!

**Comment by andydvsn** [comment]
Just a nudge from me, same error, even with su privileges.
`usb.core.USBError: [Errno 13] Access denied (insufficient permissions)`
This is macOS 10.13.6.

**Comment by ma1co** [comment]
Duplicate of #41. Please see my comment there.
