### ISSUE TITLE
Program will not install

### ISSUE THREAD

**Issue by Nikolaiwww** [ma1co/Sony-PMCA-RE#106]
ucrtbase.terminate startpoint for posedyre did not find in libary for dynamic link, api-ms-win-crt-rundtim-|1-2-0.dll. 

error message when trying to install. Tried both my computeres. I have win 7

**Comment by ma1co** [comment]
Please try installing [this](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows).
