### ISSUE TITLE
a logic question for the xpd.

### ISSUE THREAD

**Issue by surlary** [ma1co/Sony-PMCA-RE#107]
marketserver.getXpdResponse returns a struct by calling xpd.dump with 3 items(TCD, TKN, CIC), whereas marketclient.parseXpd returns a struct of 2 items(FNAME, OUS), i didn't see any common items in the xpd creation and parsing procedures. i am thinking that items created by marketserver.getXpdResponse are required by marketclient.parseXpd as 'OUS' would be used to download spk, could you help clarify?

**Comment by ma1co** [comment]
XPD is just a file format used by Sony to transmit data.
The TCD/TKN/CIC combination is used when installing apps over USB. TCD is the url to the portal and tkn is a unique id. The camera issues a request to the portal address sending the unique id. The portal returns a json response which points to the spk file to install.
The FNAME/OUS is used when installing apps through the integrated app store directly from the camera. It contains the url to the spk to install.
