### ISSUE TITLE
Access Denied - Insufficience Permissions

### ISSUE THREAD

**Issue by originalamit** [ma1co/Sony-PMCA-RE#110]
Tried running versions 16 and 17. Getting USB Permission Error. Screnshot attached. Kindly help solve this.

<img width="1680" alt="screen shot 2018-08-13 at 7 51 29 pm" src="https://user-images.githubusercontent.com/7887567/44037637-6ed65de2-9f32-11e8-9647-ed86d157eb48.png">

**Comment by originalamit** [comment]
I ran this on sony A6300 running firmware 2.1

**Comment by White-Sheep** [comment]
Did you solve this problem?

**Comment by dalekurt** [comment]
I'm also experiencing with the ILCE-6300 running Ver. 201

**Comment by ell654** [comment]
I have the same issue. Did you solve it?
