### ISSUE TITLE
Sony A6000 TimeLaps App is not counting right

### ISSUE THREAD

**Issue by djahnarnie** [ma1co/Sony-PMCA-RE#111]
The counter is always counting in 2 steps.
Lets say shots is set to 10, it will take only 5 images.

Also the auto focus light will still go on, although is set it to off in the menu.

EDIT: I figured it out, why. You need to have switch the picture control view set to off or shorter than the interval.

**Comment by account-007** [comment]
The file pmca-console-v0.17-win.exe contains the following virus: Trojan:Win32/Zpevdo.A
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

**Comment by marvinborner** [comment]
If you fixed the issue yourself, please close this issue.
