### ISSUE TITLE
pmca-console-v0.17-win.exe contains the following virus: Trojan:Win32/Zpevdo.A

### ISSUE THREAD

**Issue by account-007** [ma1co/Sony-PMCA-RE#112]
The file pmca-console-v0.17-win.exe contains the following virus: Trojan:Win32/Zpevdo.A
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

**Comment by ma1co** [comment]
This seems to be a false positive. Reported to Microsoft.

**Comment by ma1co** [comment]
Response from Microsoft: "We have reviewed the file and we have removed the detection."
