### ISSUE TITLE
usb.core.USBError:[Erroro 13] Access Denied

### ISSUE THREAD

**Issue by neskuno** [ma1co/Sony-PMCA-RE#113]
α7s2  ver 3.00

using PMCA-gui v0.17, but cannot instal OpenMemories:Tweak.

anybody same? help pls

**Comment by ellikeener** [comment]
I'm experiencing the same issue. 

Is anyone able to address this? Please help 😅

**Comment by SergioCarabantes** [comment]
same here

**Comment by Backpackstudio** [comment]
What is your operating system?

**Comment by ma1co** [comment]
Duplicate of #41. Please see my comment there.
