### ISSUE TITLE
app download

### ISSUE THREAD

**Issue by pynkstyle** [ma1co/Sony-PMCA-RE#13]
Can I somehow download an apk from one of my cameras and later install in other?

**Comment by lullibi** [comment]
you can download at least apps from the official store
at first i couldnt find the donwload location but after a search of the name (its given in the console `App written to *.apk`) i foud it in C:\Users\[USERNAME]

**Comment by ma1co** [comment]
@pynkstyle You can probably use some file explorer app to search for the apks on your camera.

@lullibi What do you mean by the installation restriction?

**Comment by lullibi** [comment]
that according to sony (they even confimed that in a mail) you only buy 10 installations and not a program. meaning you can install every program only 10 times and have to rebuy it for further installs.

BUT i bought an app and installed it a vew months ago via the official way, and then downloaded it now via pmca market and the counter still showed 1/10 installations...? you see the counter, when you log in and go to "my apps"

**Comment by lullibi** [comment]
according to sony (i even got it confirmed via mail) you can only install each app 10 times, and you have to rebuy the app again for further installs.

BUT i installed a bought app a few months ago and now downloaded it via console and the counter (you can find the counter when you log in -> "my apps") it still showed 1/10....

**Comment by ma1co** [comment]
Maybe you can only install it on different 10 cameras?

**Comment by lullibi** [comment]
that would be my thougt too, but via email they told me explicitely i can install it only ten times (i asked very specific!).... nevermind .. :)
