### ISSUE TITLE
Sony CX675: Mass storage error: Sense 0x2 0xff 0xff; Unknown device

### ISSUE THREAD

**Issue by dloprios97** [ma1co/Sony-PMCA-RE#133]
Hi
Everytime I try to install an app this error pops up using my camera HDR-CX675

Using MTP mode
`pmca.usb.InvalidCommandException: MTP error 0x2006`
Using Mass Storage Mode:
`pmca.usb.UnknownMscException: Mass storage error: Sense 0x2 0xff 0xff`

Even when I try to use the Tweak I got this:
```
Getting device info
Using firmware for model HDR-CX675

Unknown device: HDR-CX675
```

Is it something am I doing wrong? I'm on Mojave btw. I've tested on Windows 10 too.. Same. Using latest build.

Thanks in advance.

**Comment by ma1co** [comment]
Continued in #135
