### ISSUE TITLE
Sony PJ800/810/820 will it work?

### ISSUE THREAD

**Issue by eddieliuy** [ma1co/Sony-PMCA-RE#134]
Just wondering if this will work on PJ800, trying to change the language from Japanese to English, 
it doesn't seem to have the option to install apps, but i can see PJ410/440, PJ620/670/675/680 on the list. Ive tried installing the app, doesn't seem to recognize the camera, is there anything i should do first?

**Comment by ma1co** [comment]
I'm not sure if changing the language is possible. But if you want to, we can try to dump the firmware as a first step. First, we have brute force the model id of your camera. This won't install anything on your device. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
* Download [0x41010000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/2928160/0x41010000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x41010000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by wasilus** [comment]
Hi,
I tried to upload the OppenMemories Tweak on my Sony 810 but I only get this:
Querying MTP device
Sony Corporation HDR-PJ810E is a camera in MTP mode

Model:              HDR-PJ810E
Product code:       0002432414
Serial number:      03584576
Firmware version:   1.00

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation HDR-PJ810E is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006


Then I tried the command you described above, and it found a matching firmware:


Querying MTP device
Sony Corporation HDR-PJ810E is a camera in MTP mode

Getting device info
Model name: HDR-PJ810E

Trying 100 firmware images
Firmware update error: Invalid region
Success: Found matching file: gen3_0x41010032_1.dat

-------------------------------------------------------
 What steps do  I need to do further to install the tweak?
Thank you

**Comment by ma1co** [comment]
Thank you, the PJ810 is now supported in updatershell.

The next step is to dump the firmware. Here's how to do that:

* Download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).
* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot1` to `boot5` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by eddieliuy** [comment]
hello ive tried your steps from the first post on my PJ800 and got this

C:\Sony hack>pmca-console-v0.17-15-g94bde98-win.exe guess_firmware -f 0x41010000.zip
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation HDR-PJ800 is a camera in MTP mode

Getting device info
Model name: HDR-PJ800

Trying 100 firmware images
Firmware update error: Invalid region
Success: Found matching file: gen3_0x41010032_1.dat

what step should i do next

**Comment by ma1co** [comment]
The HDR-PJ800 is now also supported in updatershell. See my second message for further instructions.

**Comment by wasilus** [comment]
I uploaded the files on your dropbox. 
What is the next step?

**Comment by eddieliuy** [comment]
I have also uploaded the files for PJ800 onto dropbox ~!

**Comment by wasilus** [comment]
hello, is this dead?

**Comment by Akila3** [comment]
uploaded you my HDR-CX700V for you to add support to

**Comment by ma1co** [comment]
Thank you all for the dumps. In the newest [development builds](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), the cameras should be supported through the "Tweaks" tab in pmca-gui or the `updatershell` command on pmca-console.
