### ISSUE TITLE
CX675 Fw dump

### ISSUE THREAD

**Issue by dloprios97** [ma1co/Sony-PMCA-RE#135]
Hi again. 

I'm trying to dump the firmware of my camera (HDR-CX675) but it has been impossible.
As per devices.yml my camera is not there. Even when PJ675 is, and these two cameras are almost similar.
So my camera should be there on that list

I've tried guess firmware with this [0x61010000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/1738472/0x61010000.zip) but keeps saying: 

> Getting device info
Model name: HDR-CX675
Trying 100 firmware images
**Firmware update error: Invalid region**
Success: Found matching file: gen3_0x61010032_0.dat

I'm willing to help! What can I do?

**Comment by ma1co** [comment]
Thank you for the dump! The CX675 is now supported in updatershell.
