### ISSUE TITLE
Cannot execute on windows

### ISSUE THREAD

**Issue by electronicsguy** [ma1co/Sony-PMCA-RE#14]
On Windows 7 64-bit, v0.6 gives the error "Failed to execute script".

**Comment by lullibi** [comment]
i also tried on win 7 64bit (and on win10 its not working either)
pmca-gui-v0.6 throws "Failed to execute script" (on win7 + win10)
and
pmca-console-v0.6 (only tested on win7 64bit):
`usage: pmca-console-v0.6-win.exe [-h] [--version]
                                                          <info,install,market,apk2spk,spk2apk> ...
pmca-console-v0.6-win.exe: error: too few arguments`

the console closes almost immedeately after showing this error.

i alos tested both with compability mode, but it doesnt change anything.

**Comment by lullibi** [comment]
hm..... i found out whats not working ;)
 just opening the exe doesnt work, you need to open it in cd with arguments:

1. open the console (start+r -> cmd -> enter)
2. type in your path to "pmca-console-v0.6-win.exe" on my computer it looked like C:\Users\[username]\Downloads\pmca-console-v0.6-win.exe
3. add one of the commands from readme (like "market")
4. hit enter

summary:
1. open console (start+r -> cmd)
2. enter: `....pmca-console-v0.6-win.exe market"`

**Comment by electronicsguy** [comment]
Yes its connected in MTP mode. Console works with 'market'm gets the auth token. But nothing else can be done, since when we use the 'market -t <token>', it says no devices connected.

In summary: neither GUI nor console mode actually work to download anything on the camera. Error message in Issue #15

**Comment by lullibi** [comment]
hm... just some thoughts: i hope one might help:
- some usb cables dont support data transfer
- i tried both modes and sometimes it didnt want to install, but after repeating a several times it worked, i also used the console and the gui
- try the browserinstall
- try win10 (its for free till 30.07.16 ;) ) maybe in a virtual box

i dont really understood what you wrote about "market -t" (that command doesnt exist, right? at least thats what the console tells me). when you use the market command you dont need to connect a device to donwload a apk. you can simply download the apk and install it via the install command

final thought: i tried win7 and win10 and on win7 it didnt worked for me as well, so maybe thats the problem ...

**Comment by electronicsguy** [comment]
I don't think it's any problem with the USB cable. Installing from the official Sony playmemoriescameraapps store works perfectly, so we can rule that out.

I tried several times, no use. There is a fundamental underlying problem.

the "-t" switch is not documented, but it is there. In fact when you do "market" for the first time, and it successfully returns the auth token, the message contains a line saying "you can use this with the -t option". That's what I did. What happens is, it uses that token to communicated with Sony Entertainment Network directly, so you don't have to re-authenticate with email and password.

It's just that it doesn't actually work since it says no device connected.

**Comment by lullibi** [comment]
ah thats a nice feature with the t... now i know why it didnt work for me because i didnt generate a token at first...

now i tried it again: market -> login -> `1 devices found` but i didnt plugged it in via usb, so i guess the camera has to be "linked" to the account??

**Comment by electronicsguy** [comment]
Funny thing is, my camera is linked to that account :)

**Comment by lullibi** [comment]
maybe someone else knows better?
but if you try win10 please keep us posted :) im curious if that does the trick, although it would be strange..

**Comment by ma1co** [comment]
The first error ("Failed to execute script" when launching pmca-gui) is probably due to [this bug](https://github.com/pyinstaller/pyinstaller/issues/1957): I'm going to try to fix it by reverting to an older pyinstaller version (again).

 The `pmca-console market` command doesn't scan your usb devices. It just lists the cameras linked to your sony account (the list on the left hand side [here](https://www.playmemoriescameraapps.com/portal/usbmyapp.php)). You'll have to install an app on the official site first.

Use the `pmca-console install command` to actually install apps over usb.

**Comment by ma1co** [comment]
The gui should work now on windows 7, too. You can download the newest build on [appveyor](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). Please try and let me know if it works.

**Comment by ma1co** [comment]
I just released v0.7. The issue should be fixed.

**Comment by bardanrayhanibrahim** [comment]
pmca-console-v0.17.win.exe keeps closing itself while opening; also with cmd. Can someone enlighten me, lol :)

**Comment by tr0pm834** [comment]
@bardanrayhanibrahim did you ever figure this out, i am stuck as well
