### ISSUE TITLE
FDR-AX33 not supporting Apps?

### ISSUE THREAD

**Issue by RealTadango** [ma1co/Sony-PMCA-RE#145]
It reports a timeout when switching, the camera does nothing. The tweak tool works and all boxes can be set / unset. 

EU PAL FDR-AX33 model.

**Comment by ashmkuk** [comment]
Are you trying to switch to 60fps? 

Try this, works for AX53 so may work for 34. 
https://youtu.be/vUZtZ8bRXB0

**Comment by RealTadango** [comment]
Thanks, it worked to switch top 60P mode. The trick is to put the camera in 24p mode and then toggle the check to off using the tweaks app.
