### ISSUE TITLE
Sony DSC-HX200V

### ISSUE THREAD

**Issue by TrololoManPL** [ma1co/Sony-PMCA-RE#146]
Hi,
is it possible to add support for DSC-HX200V? I can see many different, but similar models from 2012 on the list. 
Thanks

**Comment by ma1co** [comment]
As a first step, we'd have to dump the AS300 firmware. We'll do this using the firmware update mode. First, we have brute force the model id of your camera. This won't install anything on your device. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
* Download [0x21020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3199140/0x21020000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x21020000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by TrololoManPL** [comment]
Hi,
sorry for delay. Here is the output:
`Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Model name: DSC-HX200V

Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen2_0x21020060_0.dat`
What should I do next?

**Comment by ma1co** [comment]
Thank you, the HX200V is now supported in updatershell.

The next step is to dump the firmware. Here's how to do that:

* Download the newest development build of pmca-console.
* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot1` to `boot5` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by ma1co** [comment]
@TrololoManPL Any luck?

**Comment by udippel** [comment]
Just stepping in ... maybe it was too difficult for the OP?

After the really great experience and good success experienced with the HX9V, I have in the meantime bought a HX200V, for its more advanced features. Since it also stops recording, I found out that it doesn't run Android. 
So, with the experience with the HX9V as background, I did the same with the HX200V, and am currently uploading the nflasha and a boot1 from this camera.
Hopefully, this helps to advance the performance for the HX200V, too, for me and for the OP. ;-)

Kind regards,

Uwe

**Comment by TrololoManPL** [comment]
First of all, once again sorry for the delay. It was because the camera isn't mine, I don't even have it at home. 
Secondly, I also dumped the firmware and uploaded it to the Dropbox. Hope it helps.

**Comment by 0sdelta0** [comment]
Is there any update? I also need to upgrade firmware, at least rebuild it. My DSC-HX200V UI has gotten crazy. Factory reset didn't solve anything :(

Check this thread:
https://www.dpreview.com/forums/post/51367124

**Comment by TITAN5000** [comment]
Good afternoon. Will there be a firmware for the HX200V???

**Comment by ma1co** [comment]
Again, the HX200V is supported in updatershell / pmca-gui through the "Tweaks" tab.

**Comment by TITAN5000** [comment]
there is no result, it is not stitched
