### ISSUE TITLE
Support for DSC-HX350

### ISSUE THREAD

**Issue by alex9099** [ma1co/Sony-PMCA-RE#148]
Hi,

Any plans for supporting HX350?

**Comment by alex9099** [comment]
I found this http://oss.sony.net/Products/Linux/DI/DSC-HX350.html though I guess it wouldn't help :(

**Comment by ma1co** [comment]
As a first step, we'd have to dump the firmware. We'll do this using the firmware update mode. First, we have brute force the model id of your camera. This won't install anything on your device. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
* Download [0x61020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3277480/0x61020000.zip)
 and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x61020000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by alex9099** [comment]
Thanks, i would give it a try, but, i'm on linux, would wine work on that?

**Comment by ma1co** [comment]
Thanks for trying. Please try these two files, too:
[0x41020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3279879/0x41020000.zip)
[0x51020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3279881/0x51020000.zip)

**Comment by alex9099** [comment]
There you go:

```
[alexandre@mylaptop Sony-PMCA-RE]$ python pmca-console.py guess_firmware -f 0x41020000.zip
No native drivers available
Using drivers libusb-MSC, libusb-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX350 is a camera in MTP mode

Getting device info
Model name: DSC-HX350

Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen3_0x41020023_0.dat
```

Though it says invalid version, what would that mean?

**Comment by ma1co** [comment]
Thank you, the HX350 is now supported in updatershell.

The next step is to dump the firmware. Here's how to do that:

* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot1` to `boot5` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by alex9099** [comment]
This is putting me as nervous as when i did the CFW thing on my PSP (not really knowing what to expect when running the script) :D 

Anyway, i just sent you the files, flash2 to flash4 are empty, not sure if that is expected

**Comment by ma1co** [comment]
Thank you for the dump! Everything is as expected (if you want, you can unpack the files using fwtool). Sadly, there is no Android on the camera, so it won't be possible to run apps (I expected it to be similar to the HX400, which meant there was a chance it ran Android in the background).
However, the tweaks should work, either in updatershell in pmca-console or using the tweaks tab in pmca-gui.

**Comment by alex9099** [comment]
Hmm it is giving a time out when i click on the start tweaking button (it also did give a timeout the first time i tried to run updatershell)

**Comment by ma1co** [comment]
Thank you for the feedback!

The only known issue is that a factory reset may crash the camera if protection is disabled. So make sure you re-enable protection after changing any settings.

**Comment by alex9099** [comment]
About the settings unlock (or something to show hidden settings, i don't recall) i didn't notice anything different (besides the demo mode being blocked, not sure if it already was).

Which kind of settings should appear when the hidden settings is ticked?
