### ISSUE TITLE
Error with pmca-console info

### ISSUE THREAD

**Issue by electronicsguy** [ma1co/Sony-PMCA-RE#15]
This is the error I get when I run pmca-console info:

>pmca-console-v0.6-win.exe info
Using Windows drivers
Looking for Sony devices
Querying MTP device
Sony Corporation ILCE-6300 is a camera in MTP mode
Traceback (most recent call last):
  File "pmca-console.py", line 51, in <module>
  File "pmca-console.py", line 39, in main
  File "pmca\commands\usb.py", line 132, in infoCommand
  File "pmca\usb\sony.py", line 128, in getCameraInfo
  File "pmca\usb\sony.py", line 122, in _sendCommand
  File "pmca\usb\sony.py", line 77, in sendSonyExtCommand
  File "pmca\usb\__init__.py", line 58, in _checkResponse
Exception: Response code not OK: 0x2019
Failed to execute script pmca-console

**Comment by lullibi** [comment]
did you set your device to mtp or massstorage mode (usually its preset to auto!)
also try both modes
my camera worked quite fine in masstorage mode

**Comment by ma1co** [comment]
PTP error 0x2019 means "device busy". Your computer is too fast for your camera :)

I know I should fix this, but I'm not too sure how the driver is supposed to react. For now, you can try to re-run it a few times, or switch to mass storage mode.

**Comment by electronicsguy** [comment]
@ma1co  how do I pick mass storage mode? Is it a setting on the camera or on the computer?

**Comment by lullibi** [comment]
on the camera (mine is in german but i hope its the same):
menu ->last tab (with the toolbox) -> tab No. 2 -> last point (usb-connection) -> mass storage

**Comment by ma1co** [comment]
Should be fixed in v0.7

**Comment by electronicsguy** [comment]
@ma1co thanks. works perfectly now
