### ISSUE TITLE
Support for DSC-WX350

### ISSUE THREAD

**Issue by mschut** [ma1co/Sony-PMCA-RE#150]
I am afraid the DSC-WX350 doesn't support the Android apps, does anyone have anoher suggestion how to upload from the camera to a ftp-server/synology of Google Photo's?

Ideas would be greatly appreciated

**Comment by ma1co** [comment]
The WX350 doesn't support apps, so it is almost impossible to make something like this work. However, tweaking should already work through the firmware update functionality in pmca-gui.
