### ISSUE TITLE
SONY DSC HX9V

### ISSUE THREAD

**Issue by udippel** [ma1co/Sony-PMCA-RE#152]
Hi,

I tried the standard way to remove the clip length limit from my preferred HX9V, to no avail. 
Then I followed your suggestion given in #146.

This is what I found:

pmca-console-v0.17-19-g4f89bbe-win.exe guess_firmware -f 0x21020000.zip
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX9V is a camera in MTP mode

Getting device info
Model name: DSC-HX9V

Trying 100 firmware images
Fail: No matching file found

Can you help me any further with this, please?

Greatly appreciated,

Uwe

**Comment by ma1co** [comment]
Please try this file instead: [0x11020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3322746/0x11020000.zip)

**Comment by udippel** [comment]
Close, but no cigar:

Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen2_0x11020062_0.dat

What next?

Thanks so much until here,

Uwe

**Comment by ma1co** [comment]
Thank you, the HX9V is now supported in updatershell (the "invalid version" message is expected, the firmware files you tested all have version 1.00, so it is impossible to install them).

The next step is to dump the firmware. Here's how to do that:

* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot1` to `boot5` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by udippel** [comment]
Alas, not there yet. :-(

> pmca-console-v0.17-19-g4f89bbe-win.exe updatershell
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX9V is a camera in MTP mode

Getting device info
Using firmware for model DSC-HX9V

Unknown device: DSC-HX9V

>

Thanks very much for YOUR help!

What comes next, please?

Uwe

**Comment by udippel** [comment]
Still not ... alas.

At first it didn't work, until I thought of downloading the most recent version of pcma-console: updating from pmca-console-v0.17-19-g4f89bbe-win.exe to pmca-console-v0.17-20-gad654ae-win.exe at least accepted the updatershell

And yet, it didn't go through despite several efforts on my side:

"pmca-console-v0.17-20-gad654ae-win.exe updatershell
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX9V is a camera in MTP mode

Getting device info
Using firmware for model DSC-HX9V

Initializing firmware update
Switching to updater mode

Waiting for camera to switch...
Please follow the instructions on the camera screen.
[Here a display on the camera screen pops up: 'Initialize this camera to update firmware OK'
I press the button and the camera screen turns black. After some seconds the PC shows]]
Operation timed out. Please run this command again when your camera has connecte
d."
Then the camera is stuck completely and needs to be reset by removing the battery.

I have tried another time to paste the pull /dev/nflasha into the terminal after 'OK' and below "Please follow the instructions on the camera screen." but it was not echoed and seemingly not processed in all cases, since it was considered as a subsequent system command of Windows ('not found').

What else can I do? Is there still hope?

Looking forward to getting closer ... :-)

Uwe

**Comment by ma1co** [comment]
What happens if you run the same command again after it says "Operation timed out" (without resetting the camera)?

**Comment by udippel** [comment]
Ran it twice, doing 'OK' on the instruction on the screen:

pmca-console-v0.17-20-gad654ae-win.exe updatershell
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX9V is a camera in MTP mode

Getting device info
Using firmware for model DSC-HX9V

Initializing firmware update
Switching to updater mode

Waiting for camera to switch...
Please follow the instructions on the camera screen.
Operation timed out. Please run this command again when your camera has
connecte
d.

pmca-console-v0.17-20-gad654ae-win.exe updatershell
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 97, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 83, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 342, in
updaterShel
lCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 222, in
getDevice
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 190, in
listDevices

  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 30, in __init__
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 44, in reset
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\msc.py", line 219,
in s
endCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\msc.py", line 205,
in _
sendScsiCommand
pywintypes.error: (5, 'CreateFile', 'Zugriff verweigert')
[3888] Failed to execute script pmca-console

To be noted: The camera is set to MTP.
Do the subsequent settings have anything to make with this problem?:
USB Power Supply On
LUN Setting Multi

Uwe

**Comment by udippel** [comment]
Thought / hoped that much:

Used my home PC, booted to W10, with the English(UK) version installed, and
your software went through! Yippee!
Only, there was a single boot file, boot1. Is that okay? In any case, I
uploaded the zipped 2 files to your Dropbox.

Interesting enough, it went through the Mass Storage in this case. It had
NOT done so at the other place, neither.

Looking forward to your reply,

Uwe

**Comment by udippel** [comment]
I suspect the system language of the PC to have been the earlier obstacle, rather than the Windows version (W7). Unfortunately I don't have an English W7 .
The idea to try an English version sprang into my mind when I noticed the "5, 'CreateFile', 'Zugriff verweigert'" (access denied) in the error message.

**Comment by ma1co** [comment]
Thank you for the dump! I don't think the OS language is the problem. It is probably your windows version or some other software interfering.

Anyway, you should now be able to use the tweak command in updatershell or the tweaks tab in pmca-gui. I don't know if the video recording limit can be unlocked on such an old camera, but feel free to try.

**Comment by udippel** [comment]
Thanks a bunch, again!
This time I tried the v0.17-20-gad654ae on a W10 in GUI version. It went through without a hitch (see attachment).
<img width="576" alt="HX9V_20_gad654ae" src="https://user-images.githubusercontent.com/50265752/60498629-46115500-9cb7-11e9-91a1-93f51178215c.png">

And of now, it shows a movie recording of 33:15 and running ... !

I owe you one!

Wholehearted thanks from me,

Uwe
