### ISSUE TITLE
Error Installing to a6000

### ISSUE THREAD

**Issue by steve69za** [ma1co/Sony-PMCA-RE#155]
![Screen Shot 2019-08-08 at 5 49 12 PM](https://user-images.githubusercontent.com/53910495/62717955-23383600-ba05-11e9-958f-0e4b3ceef5b0.png)

Installing the app on an my a6000 generates the following error:
Exception: Wrong response type: 0x2

**Comment by schnillerman** [comment]
Switch USB connection to MTP connection. Then it should work.

**Comment by ma1co** [comment]
See #41
