### ISSUE TITLE
A6300 shutter speed change between shots

### ISSUE THREAD

**Issue by djjjo** [ma1co/Sony-PMCA-RE#158]
I was testing they app... Put my focus on manual, set my iso and shutter speed. but for some reason each shot had a different shutter speed. Why is that?

**Comment by ma1co** [comment]
Please report this in the correct repository. I cannot tell which app you are using.

**Comment by chiahsoon** [comment]
Using v0.18, I have this issue too! The shutter speeds are always 1/1000, 1/4000, 1/125.
