### ISSUE TITLE
update but still old version number

### ISSUE THREAD

**Issue by lullibi** [ma1co/Sony-PMCA-RE#16]
hi,

i downloaded an app (newer then mine on the camera) via console, then deleted the app on the camera (smartRemote 4.10) and then installed v4.20 via console.
but in the appmanager it says its still version 4.10. im not sure if it really is version 4.10 or not but anyway it shouldn't be that way...

**Comment by ma1co** [comment]
How exactly did you install it? And what does the AndroidManifest.xml say?

**Comment by lullibi** [comment]
what i did:
1. i installed SmartRemote (SR) v4.10 via the official store on my camera (beforer the era of openmemories) 
2. i downloaded SmartRemote420.apk via console
3. i deleted SRv4.10 (because with another app that i tried before i didnt delete it and it was the same bug too)
4. i installed it via console
5. i checked the version via the app manager on the camera (a5000) and it still was v4.10

what is the AndroidManifest.xml? how can i get you the information you need?

**Comment by lullibi** [comment]
i found a AndroidManifest.xml... and its probably the solution.

the AndroidManifest.xml inside the SmartRemote420.apk has much cryptic stuff and i searched it with notepad++ for 4.10 and for 4.20 and it only found 4.10!
it's the very same with the other app i also tried to update right number in apk name but "wrong" number in manifest....
what does that mean? O_o

**Comment by ma1co** [comment]
I just checked myself. Sony made an error in the apk (they didn't update the version number in the manifest i guess). It doesn't matter how you install it, you'll get the same result if you install it from the official store.

To decompile apk files, use [jadx](https://github.com/skylot/jadx) or their [online service](http://www.javadecompilers.com/apk).

**Comment by obs1dium** [comment]
It definitely shows up as 4.20 on my camera. They didn't bother incrementing the versionCode, but the versionName is set to 4.20 in the manifest.
I can't test with pmca-console's market feature, though, as that always reports 0 devices for me.

**Comment by ma1co** [comment]
I checked again. It seems that they don't return the same apk depending on your camera model. If you use the official market app on your camera, you can see the version that will actually be installed. My A6000 for example would only install SmartRemote 4.10, i guess 4.20 is for newer cameras only. I changed the filename handling, the `pmca market` command should now report the correct filename.

@obs1dium Can you try the [newest build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts) and tell me if it lists your devices? f307d06b154bc3f1fa5760d3be4a4c64498ad15e might have fixed it.

**Comment by obs1dium** [comment]
Nope, still says 0 devices. However, when logging in through the browser, [this page](https://www.playmemoriescameraapps.com/portal/usbmyapp.php) does not show any 'authenticated cameras', even though I downloaded apps before, so it could be a problem on their end.

**Comment by lullibi** [comment]
hm with the update 0.7 i now also have 0 devices??????? befor it worked fine with version 0.6..?

**Comment by lullibi** [comment]
but 0.6 doesnt seem to work either now?!?
`0 devices found`

**Comment by ma1co** [comment]
@lullibi Does [this page](https://www.playmemoriescameraapps.com/portal/usbmyapp.php) show the camera in the left sidebar?

**Comment by lullibi** [comment]
you're right! my camera has vanished! :confused:
