### ISSUE TITLE
Sony DSC- HX30V Japanese Language

### ISSUE THREAD

**Issue by superbroken** [ma1co/Sony-PMCA-RE#164]
i have my aunt camera it is SONY DSC HX30V and my problem is it is japenese language

i try the gui pmca v.17 and no luck at all stuck at error message

MTP error 0x2006

**Comment by ma1co** [comment]
@superbroken We can add the HX30V, but there is some work we have to do first. As a first step, we'd have to dump the firmware. We'll do this using the firmware update mode. First, we have brute force the model id of your camera. This won't install anything on your device. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
* Download [0x21020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3199140/0x21020000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x21020000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by halinh12sinh** [comment]
> @superbroken We can add the HX30V, but there is some work we have to do first. As a first step, we'd have to dump the firmware. We'll do this using the firmware update mode. First, we have brute force the model id of your camera. This won't install anything on your device. If you're interested to help, here's what you can do:
> 
> * If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
> * Download [0x21020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3199140/0x21020000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
> * Power on your camera and connect it over USB to your computer.
> * Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x21020000.zip`
> * With a bit of luck, the script should find the model id of your camera.
> 
> Let me know if you need any help.

Hi @ma1co , I am using a Sony DSC-RX1R which is listed on supported devices. 
 DSC-RX1R:
  gen: 2
  model: 0x22020024
But when I extracted the file 0x21020000.zip , I found gen2_0x21020024_0.dat instead of 0x22020024. Any mistake here?What should I do? Should I rename gen2_0x21020024_0.dat  to gen2_0x22020024_0.dat and update firmware for the camera?
Please advise.
Thank yo so much.

**Comment by illogique** [comment]
hello just got this camera...

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Model name: DSC-HX30V

Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen2_0x21020050_0.dat

**Comment by ma1co** [comment]
@illogique Thanks, the DSC-HX30V should now be supported in updatershell (even though no tweaks are available). It looks like this camera uses the same firmware as the HX20V, but I forgot to add it to the list.

**Comment by HCX-star** [comment]
Hello, I am now giving my Sony RX1r to update the language, have you solved it? I want to ask, because when I use the gui it shows that the installation of the driver failed, I don't know what the reason is, I want to solve this problem, can you give me an answer if you see it? Thank you/

**Comment by HCX-star** [comment]
> > @superbroken我们可以添加HX30V，但是我们必须先做一些工作。作为第一步，我们必须转储固件。我们将使用固件更新模式执行此操作。首先，我们暴力破解了相机的型号ID。这不会在您的设备上安装任何内容。如果您有兴趣提供帮助，可以执行以下操作：
> > 
> > * 如果您使用的是 Windows，请[在此处](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts)下载 pmca-console 的最新开发版本。如果您使用的是OS x，则必须等待下一个版本（抱歉）。
> > * 下载[0x21020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3199140/0x21020000.zip)并将其放在同一文件夹中（无需解压缩）。它包含一堆可能与您的相机匹配的固件映像。
> > * 打开相机电源并通过USB将其连接到计算机。
> > * 打开命令提示符并运行以下命令：`pmca-console guess_firmware -f 0x21020000.zip`
> > * 运气好的话，脚本应该会找到相机的型号 ID。
> > 
> > 如果您需要任何帮助，请告诉我。
> 
> 嗨@ma1co，我正在使用受支持的设备上列出的索尼 DSC-RX1R。DSC-RX1R：gen： 2型号： 0x2**2**020024但是当我0x21020000.zip提取文件时，我发现gen2_0x2**1**020024_0.dat而不是0x22020024。这里有什么错误吗？我该怎么办？我是否应该将gen2_0x21020024_0.dat重命名为**gen2_0x2 2**020024_0.dat并更新相机的固件？请指教。非常感谢你。

**Comment by HCX-star** [comment]
> > @superbroken我们可以添加HX30V，但是我们必须先做一些工作。作为第一步，我们必须转储固件。我们将使用固件更新模式执行此操作。首先，我们暴力破解了相机的型号ID。这不会在您的设备上安装任何内容。如果您有兴趣提供帮助，可以执行以下操作：
> > 
> > * 如果您使用的是 Windows，请[在此处](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts)下载 pmca-console 的最新开发版本。如果您使用的是OS x，则必须等待下一个版本（抱歉）。
> > * 下载[0x21020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3199140/0x21020000.zip)并将其放在同一文件夹中（无需解压缩）。它包含一堆可能与您的相机匹配的固件映像。
> > * 打开相机电源并通过USB将其连接到计算机。
> > * 打开命令提示符并运行以下命令：`pmca-console guess_firmware -f 0x21020000.zip`
> > * 运气好的话，脚本应该会找到相机的型号 ID。
> > 
> > 如果您需要任何帮助，请告诉我。
> 
> 嗨@ma1co，我正在使用受支持的设备上列出的索尼 DSC-RX1R。DSC-RX1R：gen： 2型号： 0x2**2**020024但是当我0x21020000.zip提取文件时，我发现gen2_0x2**1**020024_0.dat而不是0x22020024。这里有什么错误吗？我该怎么办？我是否应该将gen2_0x21020024_0.dat重命名为**gen2_0x2 2**020024_0.dat并更新相机的固件？请指教。非常感谢你。

Hello, I am now giving my Sony RX1r to update the language, have you solved it? I want to ask, because when I use the gui it shows that the installation of the driver failed, I don't know what the reason is, I want to solve this problem, can you give me an answer if you see it? Thank you/

**Comment by noahsboring** [comment]
@ma1co , I am having an issue with the DSC-HX30V. It gets recognized in pcma-gui v0.18, but whenever I go to the "tweaks" tab and click on "start tweaking (updater mode), it now says "unknown device: DSC-HX30V". Please, is there anything you could do to help me? I have been working on this for a couple hours now and I can't seem to fix it myself. Apologies in advance as this is the first time I am attempting anything like this.

**Comment by lala0tara** [comment]
hello,

I receive a gift from my tita, a sony cybershot DSC-HX30VN and when i tried to change the language it only show one choice "Japanase Standard" i dont know what to do next i dont know how to operate and to unlock languega of english to this . Could you me really fast?
