### ISSUE TITLE
Issue on RX100M3

### ISSUE THREAD

**Issue by dgiaffe** [ma1co/Sony-PMCA-RE#175]
Hey, this is really far fetched, but I am reaching out to you because you seem very knowledgeable with the Sony cameras.

You see, I tried to update my camera to the version 2.00 and something went wrong with the update process, I am not sure what. It told me that the update failed, and now, my camera doesn't fully power on anymore. I can see the power button light up as son as there is power to it (I can't turn it off), and nothing else happens (no LCD, the lens doesn't expand either). I tried to reflash multiple times, with different computers, but no luck. 

Now, I stumbled upon your repository and figured I'd try your PMCA-gui or console to see if I can get anything else. Turns out any parameter with the console gives me the following: 

```
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0
[8848] Failed to execute script pmca-console
```

The gui gives me the following log when trying to update with it: 

```
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in updater mode

Initializing firmware update
Updating from version 1.20 to version 2.00
Writing firmware
0%
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 100, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 337, in firmwareUpdateCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 414, in firmwareUpdateCommandInternal
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 542, in writeFirmware
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 492, in _sendWriteCommands
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 479, in _sendCommand
Exception: Response error: 0x1049

```
I believe my partition is corrupted. Do you happen to know which format Sony uses? I'll see if I can run a tool to recover it. Now I totally get you don't owe me anything and it's not directly related to the tools you develop, but if you happen to have some time, that would be greatly appreciated. Wasn't sure how to reach out to you out of here. 

Thanks in advance!

**Comment by ma1co** [comment]
Your camera is currently booting into the updater partition, that is why you have the black screen.
The following command should work:
`pmca-console updatershell -m DSC-RX100M3`
You can use the `shell` subcommand to open a shell on the device to try to find out what is corrupted.

If AND ONLY IF you are confident that nothing is corrupt, you can delete the `/setting/updater/mode` file. This stops the camera from booting into the updater partition (the file is usually removed at the end of a firmware update). However, once you have done this, there is no known way to go back to the updater mode. If something is corrupt and the camera cannot boot from the main partition, it is bricked.

Sadly, I don't really know how to easily check the partitions for corruption... How far into the firmware update did it crash?

**Comment by dgiaffe** [comment]
Hi there, thank you SO much for replying. I can reach the shell with your command! That brings a lot of hope hehe. As far as I remember, It failed on the "Run the update" step, but I don't believe it had the time to do anything. I hit the reset camera step, but mistakenly unplugged the cable (they say to "safely remove hardware but keep the usb cable connected") and plugged it again. Then I hit the Run step and it failed. So I guess I will give it a try. Thanks a bunch for your advice!

**Comment by dgiaffe** [comment]
Thank you  SO SO much! I am back in the main partition. Your tool saved my device, truly appreciate it! Any way I can donate you anything? Thanks!

**Comment by ma1co** [comment]
I'm glad it worked! I have never accepted any donations in the past, but as a trial, I have installed the following page where you can donate to charity instead. Please consider it, I get notifications about the donations and it greatly boosts my motivation! https://www.globalgiving.org/fundraisers/ma1co/

**Comment by dgiaffe** [comment]
You truly are a great person! I've donated to coding hehe. Thank you again!!

**Comment by dgiaffe** [comment]
You truly are a great person! I've donated to coding hehe. Thank you again, and have a wonderful weekend!

**Comment by ma1co** [comment]
Thank you very much for the generous donation!
