### ISSUE TITLE
Sony DSC-TX7

### ISSUE THREAD

**Issue by michal9680** [ma1co/Sony-PMCA-RE#176]
Hello, i kindly ask you to please add DSC-TX7 to supported cameras.
The firmware for this camera is gen2_0x21020000_0.dat

**Comment by ma1co** [comment]
Can you please send me the output of `pmca-console guess_firmware`, just to make sure?

**Comment by michal9680** [comment]
> 

    Using drivers Windows-MSC, Windows-MTP
    Looking for Sony devices

    Querying mass storage device
    Sony DSC is a camera in mass storage mode

    Getting device info
    Model name: DSC-TX7

    Trying 100 firmware images
    Firmware update error: Invalid version
    Success: Found matching file: gen2_0x21020000_0.dat

> 
This was the output of 

> pmca-console guess_firmware -f 0x21020000.zip

**Comment by ma1co** [comment]
Done. If possible, please send me a firmware dump. Here's how to do that:

* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot1` to `boot5` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by michal9680** [comment]
`pmca-console updatershell` either hangs on querying device, or says that DSC-TX7 is not supported

**Comment by ma1co** [comment]
Are you using the [latest development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts)?

**Comment by michal9680** [comment]
Here is the output of `pmca-console updatershell` on latest development build

```
Getting device info
Using firmware for model DSC-TX7

Initializing firmware update
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 97, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 83, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 363, in updaterShel
lCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 376, in firmwareUpd
ateCommandInternal
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 527, in checkGuard
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 492, in _sendWriteComma
nds
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 471, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 66, in sendSonyExtComma
nd
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\msc.py", line 223, in s
endWriteCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\msc.py", line 208, in _
sendScsiCommand
ValueError: Buffer size too small (3 instead of at least 44 bytes)
[7360] Failed to execute script pmca-console
```
Then camera freezes

**Comment by ma1co** [comment]
I have just noticed that the DSC-TX7 was released in 2010. There is no way this camera is gen2. I don't know why it gave you this result with `guess_firmware`. Please try that command again with this zip file: [0x10210100.zip](https://github.com/ma1co/Sony-PMCA-RE/files/4187939/0x10210100.zip)

**Comment by michal9680** [comment]
Sorry for late response. Heres the output of `pmca-console guess_firmware -f 0x10210100.zip`

```
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Model name: DSC-TX7

Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen0_0x10210102_0.dat
```

**Comment by ma1co** [comment]
Updated. Can you try again?

**Comment by michal9680** [comment]
After running `nflasha` and `bootloader` commands i've got two files nflasha and boot1 . I packed them into DSC-TX7.zip, and send them into your dropbox

**Comment by ma1co** [comment]
Thank you for the dump!
Sadly, the TX7 is very old, so there are no tweaks available...

**Comment by michal9680** [comment]
Damn, I was kinda hoping for pal/ntsc switch, but i'm glad I helped you anyway.

**Comment by shohei0308** [comment]
Hello.
I'm Japanese, so I'm sorry for my poor English.
I want to change the Japanese version of TX7 to English.
Do you have any good firmware or code?
Please let me know if you know.

Thank you!
