### ISSUE TITLE
DSC-HX9V MTP SendCommand failed

### ISSUE THREAD

**Issue by guidonero** [ma1co/Sony-PMCA-RE#182]
pmca-gui-v0.17-win.exe recognizes the camera in MTP mode as DSC-HX9V but fails to communicate, returning  "Exception: MTP SendCommand failed: 0x-7ff8ffe1"
Also, under the Tweaks tab, Start tweaking (updater mode) returns error, "Unknown device: DSC-HX9V"

**Comment by ma1co** [comment]
The HX9V should be supported in the newest [development builds](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts) under the tweaks tab.
