### ISSUE TITLE
Is the tweak possible on the a6600 ? 

### ISSUE THREAD

**Issue by nikdek69** [ma1co/Sony-PMCA-RE#184]
Hi, sorry but I can't find any list of the supported models
Is it possible ?

Because I only get errors while trying

thanks

**Comment by 54696d21** [comment]
no, it is not supported

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
