### ISSUE TITLE
Sony a6400 support

### ISSUE THREAD

**Issue by mufasa08** [ma1co/Sony-PMCA-RE#191]
Hey,
Could you please help get this working for a6400? 6500 and 6300 are supported and they are similar models that came out just before 6400.
If you don't have time to do this, I'm an android developer, can you just point me to what files need to be changed in order to support new device and i will fork.

**Comment by CyberUSB** [comment]
@mufasa08
The a6400 was released in 2019. The a6300 and a6500 were released in 2016. 

According to the PMCA front page:

> Additional effort has been made to analyze the firmware update process. Using the obtained knowledge, we can execute custom code on almost all Sony Cybershot and Alpha cameras released between 2007 and 2016.

So the a6400 is too new. If you want to develop your own android apps for a Sony camera, then you need to buy a camera released in 2016 or earlier.

It's good to see that you're an android developer. What kind of android apps were you hoping to develop for your Sony camera?

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
