### ISSUE TITLE
Sony a6100 Support

### ISSUE THREAD

**Issue by MamiRD** [ma1co/Sony-PMCA-RE#195]
Hola! The gui program recognizes the camera but, when I try to install an app, I get the following error code:
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0
When switching to MTP connection I get pmca.usb.InvalidCommandException: MTP error 0x2006
Is there a fix for this problem?

**Comment by wearepostmodern** [comment]
I also have this error?
Any updates?

**Comment by ma1co** [comment]
Please refer to [this issue](https://github.com/ma1co/Sony-PMCA-RE/issues/194).
