### ISSUE TITLE
DSC-RX0M2 not supported

### ISSUE THREAD

**Issue by ghost** [ma1co/Sony-PMCA-RE#199]
Hi I have an RX0ii and would live support if possible

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
