### ISSUE TITLE
Not working in Google Chrome

### ISSUE THREAD

**Issue by mgillespie** [ma1co/Sony-PMCA-RE#2]
It seems to load the browser plugin, and that's about it.

Loading plugin
Plugin loaded
Starting task
Got task key
Cancelling plugin
Plugin cancelled
Starting download to camera

**Comment by mgillespie** [comment]
Works on IE11
Not working on Chrome 42 (with NPAPI enabled)

**Comment by ma1co** [comment]
I can confirm that it doesn't work in Chrome...

**Comment by mgillespie** [comment]
To anyone watching this, Google disabled NPAPI support in Chrome from Chrome 42 onwards.   This means by default, the current versions of Chrome won't worth with this, or Sony's official Playmemoriescameraapps.com   site until you re-enable NPAPI plugins.

See here:   https://support.google.com/chrome/answer/6213033?hl=en-GB

Chrome version 45 will remove NPAPI completely, and by then, I hope Sony wil have woken up and stopped using 20 year old plugin frameworks.

**Comment by ma1co** [comment]
NPAPI, Chrome and appengine SSL certificates don't seem to play well together... I disabled https for the request that is done by the plugin. It should work now.
