### ISSUE TITLE
Openmemories: Tweak app fails to install to a6000 on MacOS Catalina 10.15.6 with SSL error

### ISSUE THREAD

**Issue by sdedalus1** [ma1co/Sony-PMCA-RE#201]
PMCA Gui v0.17 fails to install Openmemories Tweak with an SSL error when connecting to my a6000 via MTP. I can't seem to copy/paste the error message so I have attached it as a screenshot below. I also downloaded the v. 0.11 APK of Openmemories Tweak to install it locally and got the same error.
<img width="1062" alt="Screen Shot 2020-08-21 at 10 27 04 PM" src="https://user-images.githubusercontent.com/5317144/90946729-b3250400-e3fd-11ea-8816-5f616fdda245.png">

**Comment by ma1co** [comment]
Are you running the python scripts or the binaries? If you are using the scripts, please try the master branch, a1c6a67fbce24cf1c7abc88c2df9e85813b71cba might have fixed this.

**Comment by wotis** [comment]
I also have this problem and I'm running the binaries for Mac. How can I apply this fix? Or could someone compile a new version with this ssl-fix included?

**Comment by ma1co** [comment]
v0.18 has been released recently.
