### ISSUE TITLE
Sony a6100 support

### ISSUE THREAD

**Issue by wearepostmodern** [ma1co/Sony-PMCA-RE#203]
App recognizes camera in both mac and windows but gives
pcma.Usb.InvalidCommandException: Mtp error 0x2006

**Comment by Achim0017** [comment]
Using an A6400 (2020) I got similar problems, I think this is a config problem. While taking the offered Sony plugin for macOS, I tried Sony PMCA-RE v0.17, v0.16 and 15 as the gui.  The connection is fine to the CAM even in MTP USB mode, but download of the app returns with not finding sony__.py files. These phyton files are not part of the driver!? 
I tried DriverLoader1013 on top, but no difference. 
Please advise SW for relevant MACOS 10.12-10.14, 10.15, or higher.  
Related SW page is Sony-pmca.appspot.com (Jan/2021)

**Comment by ma1co** [comment]
Please check [this issue](https://github.com/ma1co/Sony-PMCA-RE/issues/194).
