### ISSUE TITLE
Does not work on AX43!!

### ISSUE THREAD

**Issue by johninstockie** [ma1co/Sony-PMCA-RE#220]
Please can you add in the AX43 to this, its the same family as the 33 and the 53, but come up as unknown camera

**Comment by Cuberlain** [comment]
ma1co won't care about video cameras, despite DSLR cameras are unable to make good quality videos. They always come up with the bukeh mania, despite the sharpness and details on DSLR-s are not even close to real camcorders.

**Comment by DBM75** [comment]
I plan to buy the FDX-AX43.
But it would be very cool, if 4K with 30fps would working.
Why is the PMCA-GUI not working with AX43?
It is listed here [as supported camcorder](https://github.com/ma1co/fwtool.py/blob/master/devices.yml)

KR
Dirk

**Comment by Cuberlain** [comment]
DSLR =Slower autofocus, problematic sound, less visible details and sharpness. As I told, DSLR maniacs always come up with their bokeh mania....

**Comment by DBM75** [comment]
@Cuberlain: Your comments didn't answer my question or I don't understand right. 
For my better understanding and am I right ?
@ma1co is only focusing on DSLR cams, not camcorders?
But why is then the FDR-AX43 listed under supported cams for PMCA-GUI with firmware update mode tweaking?
So this implies for me, the AX43 was already tweaked successful with this tool and can be switched to ntsc 30fps.

**Comment by ma1co** [comment]
The AX43 should work fine with the updater mode tab in pmca-gui. However, only the language tweak is supported, as far as I know.

**Comment by DBM75** [comment]
Thanks for you answer.
This sounds good.
Ok, then I will try with _**pmca-console-v0.17-win.exe**_ to switch to 30fps, when my AX43 is arriving in the next days.

**Comment by johninstockie** [comment]
I can confirm that it does not work on the AX43.  I have an AX43 and have
tried.  The tool lists the AX53 and AX33 but not AX43 (maybe left out by
mistake??)

**Comment by ma1co** [comment]
@johninstockie If you want any help online, please list all the steps you have tried and what went wrong, including detailed error descriptions or messages. Thanks.

**Comment by johninstockie** [comment]
@ma1co 
Any help is appreciated!!  So I followed the process as per this video here [instructions](https://www.youtube.com/watch?v=vUZtZ8bRXB0).

This is what happens when the AX43 is attached.  Even though the app recognises the camera as the AX43 in the "Camera Info" tab, clicking 'Tweak' returns an error as [shown here](https://youtu.be/UkKrOKL1vHA)

Any ideas?

**Comment by ma1co** [comment]
@johninstockie The AX43 is not supported in v0.17. Please use the [most recent build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).

**Comment by DBM75** [comment]
@ma1co Yeah - you did a great job.
My AX43, today delivered, is now enabled for 30fps with the mentioned recent built.
Thank's a lot for this tool!

**Comment by johninstockie** [comment]
Hi ma1co

ok, tried the latest version on the link you shared, seems a couple of bugs
in the code maybe??

This is what I saw from "*pmca-gui-v0.17-43-g2c24d4b-win.exe*"

On *Connecting*
Loading app list
Found 11 apps

Click *Get Camera Info*
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation FDR-AX43 is a camera in MTP mode

Model:              FDR-AX43
Product code:       0002450960
Serial number:      05645492
Firmware version:   1.01

Click *Start Tweaking (updater mode)*
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation FDR-AX43 is a camera in MTP mode

Getting device info
Using firmware for model FDR-AX43

Initializing firmware update
Traceback (most recent call last):
  File "pmca-gui.py", line 116, in do
  File "pmca\commands\usb.py", line 363, in updaterShellCommand
  File "pmca\commands\usb.py", line 376, in firmwareUpdateCommandInternal
  File "pmca\usb\sony.py", line 527, in checkGuard
  File "pmca\usb\sony.py", line 501, in _sendWriteCommands
Exception: Firmware update error: Low battery

I am charging the camera and will try again once fully charged, but hope
you have some idea of a solution?

Thanks

**Comment by johninstockie** [comment]
> @ma1co Yeah - you did a great job.
> My AX43, today delivered, is now enabled for 30fps with the mentioned recent built.
> Thank's a lot for this tool!

Dirk How???

Is not working for me at all?  Can you explain what you did, maybe a step I have missed somewhere?

Thanks

**Comment by DBM75** [comment]
1. I enabled the 24p mode in the settings installations submenu - Important!!!!!!!!!!!!!!!
2. verified that there is no more frequency option in quality/size settingsmenu and on the display ist shown 4K 24p
3. put USB to PC and wait for Windows driver installation etc. and I selected the default action for Windows to "DO NOTHING"
4. disconnect cam
5. started with admin. privileges the pmca-gui-v0.17-43-g2c24d4b-win.exe and let the EXE access to internet by firewall
6. connect cam again and clicked on get cam info
7. tweak button clicked and wait for instructions etc.
8. checked the unlock prot. settings and removed the PAL/NTSC checkmark 
9. clicked on DONE

First run was also unsuccessful for me.
I think the driver installation was not finished or the default Windows action was a problem.
But second run was all fine for me.

Have also the 1.01 FW on AX43.

Good luck.

**Comment by johninstockie** [comment]
@DBM75 , @ma1co, It Worked!!!

On 4th connect reconnect, I had to _re_-check the Enable/Disable and then uncheck once again...  Had to do twice check and uncheck fully 2x (4 usb connections) and then it just started working.

Thank you both so much for your help VERY much appreciated  👍 👍 👍

**Comment by iminko** [comment]
Hi guys, i want ask for a help. I can't find how to download pmca-gui-v0.17-43-g2c24d4b-win.exe . When click on link provided by ma1co, there is a cryptography bump or what it is but i can't see that exe file. Thanks

**Comment by DBM75** [comment]
> Hi guys, i want ask for a help. I can't find how to download pmca-gui-v0.17-43-g2c24d4b-win.exe . When I click on a link provided by ma1co, there is a cryptography bump or what it is but i can't see that exe file. Thanks

try this link here:
https://ci.appveyor.com/project/ma1co/sony-pmca-re/builds/37652552/artifacts

**Comment by iminko** [comment]
> > Hi guys, i want ask for a help. I can't find how to download pmca-gui-v0.17-43-g2c24d4b-win.exe . When I click on a link provided by ma1co, there is a cryptography bump or what it is but i can't see that exe file. Thanks
> 
> try this link here:
> https://ci.appveyor.com/project/ma1co/sony-pmca-re/builds/37652552/artifacts

thanks, everything works like a charm.

**Comment by tinhtu2012** [comment]
> > Hi guys, i want ask for a help. I can't find how to download pmca-gui-v0.17-43-g2c24d4b-win.exe . When I click on a link provided by ma1co, there is a cryptography bump or what it is but i can't see that exe file. Thanks
> 
> try this link here:
> https://ci.appveyor.com/project/ma1co/sony-pmca-re/builds/37652552/artifacts

I could not se the exe file. Would you please check if it is still there? Thank you.

**Comment by iminko** [comment]
> > @johninstockie The AX43 is not supported in v0.17. Please use the [most recent build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).
> 
> Ma1co, please help me. I could not download the exe file from the link. I bought FRD-AX60 on Ebay. I would like to change the language to English. Thanks a lot.

try this link, but it's not the most recent build: https://github.com/ma1co/Sony-PMCA-RE/releases/tag/v0.17

**Comment by tinhtu2012** [comment]
> > > @johninstockie The AX43 is not supported in v0.17. Please use the [most recent build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).
> > 
> > 
> > Ma1co, please help me. I could not download the exe file from the link. I bought FRD-AX60 on Ebay. I would like to change the language to English. Thanks a lot.
> 
> try this link, but it's not the most recent build: https://github.com/ma1co/Sony-PMCA-RE/releases/tag/v0.17

I tried that link. It did not work :-( 
Do you still have the file that you can email me? Thanks a  lot.

**Comment by iminko** [comment]
Yes, give me your email.

**Comment by tinhtu2012** [comment]
> Yes, give me your email.

@iminko tinhtuquaycuong@gmail.com. Thanks.

**Comment by tinhtu2012** [comment]
> Yes, give me your email.

Thank you so much for the file.

However, it still does not work as follow:

> Using drivers Windows-MSC, Windows-MTP
> Looking for Sony devices
> 
> Querying MTP device
> Sony Corporation FDR-AX60 is a camera in MTP mode
> 
> Getting device info
> Using firmware for model FDR-AX60
> 
> Unknown device: FDR-AX60
> 

@ma1co @mungewell  Would you please help?

**Comment by WoodyTH** [comment]
Thank you very much brother 
I am from Thailand. You saved me from buying a new camera.
After being in 25/50p mode, now Sony AX43A can use 60p mode.

Thank you very much.

Use V0.18
