### ISSUE TITLE
Sony-RX10-m4

### ISSUE THREAD

**Issue by Jeffhvac** [ma1co/Sony-PMCA-RE#221]
This loader wont work with the Sony RX10 m4 and I need to unlock the Chinese language

**Comment by Jeffhvac** [comment]
I can not get the GUI to see the Camera RX10 m4

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
