### ISSUE TITLE
Support for Sony DSC-WX300

### ISSUE THREAD

**Issue by HDCP** [ma1co/Sony-PMCA-RE#225]
Hello. Is the Sony DSC-WX300 (Firmware 1.00) supported for OpenMemories? 

I am receiving errors for both MTP and Mass Storage connections when trying to install the OpenMemories Tweak application with pmca-gui v0.16:

```
Loading app list
Found 11 apps
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices
Querying MTP device
Sony Corporation DSC-WX300 is a camera in MTP mode
```

When trying to install OpenMemories with an MTP connection, I receive this error message:
`pmca.usb.InvalidCommandException: MTP error 0x2006`

When trying to install OpenMemories with a Mass Storage connection, I receive this error message:
`pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0`

As I understand it, it is recommended to use the "Tweaks" tab in the GUI to get into updater mode first. That throws this error for me:
```
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices
Querying MTP device
Sony Corporation DSC-WX300 is a camera in MTP mode
Getting device info
Using firmware for model DSC-WX300
Unknown device: DSC-WX300
```

If you need me to check a firmware on my camera with the pmca-console, let me know.

**Comment by HDCP** [comment]
@ma1co Please let me know if I can help with this.

**Comment by ma1co** [comment]
The WX300 can probably be added. As a first step, we have to dump its firmware. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
* Download [0x31020000.zip](https://github.com/ma1co/OpenMemories-Tweak/files/2624485/0x31020000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x31020000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by HDCP** [comment]
Thank you for the response. I matched it to this:

```
Querying MTP device
Sony Corporation DSC-WX300 is a camera in MTP mode
Getting device info
Model name: DSC-WX300
Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen2_0x31020010_0.dat
```

**Comment by ma1co** [comment]
Thank you, the WX300 is now supported in updatershell.

The next step is to dump the firmware. Here's how to do that:

* Download the newest build of pmca-console.
* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by HDCP** [comment]
I have uploaded the files as requested.

**Comment by ma1co** [comment]
Thanks for the dump! You can now try to unlock the languages / video limit using the Tweak tab in pmca-gui or the tweak command in pmca-console updatershell.

**Comment by dudubets** [comment]
Hey guys, i am trying to modify the firmware from the A57 to clean the hdmi.

But at guess_firmware -f 0x31020000.zip i get no match. I got the exe firmware file, how can i extract the bat file?

**Comment by twaan076** [comment]
hi can someone help me with my DSC-W380?
