### ISSUE TITLE
Could you support Sony HDR-CX670?

### ISSUE THREAD

**Issue by johnoh125** [ma1co/Sony-PMCA-RE#227]
Hello.
I left a message on the issue of OpenMemories-Tweak,
but I am also inquiring here because there are no replies.

[https://github.com/ma1co/OpenMemories-Tweak/issues/392](url)

![104106813-60d87700-52fb-11eb-90db-a59f95015169](https://user-images.githubusercontent.com/77175109/105611523-47eebc00-5df9-11eb-96ac-8385612cff18.png)
![104106814-63d36780-52fb-11eb-9be0-af1d21598fe4](https://user-images.githubusercontent.com/77175109/105611534-5046f700-5df9-11eb-8d26-25fe89bab9f6.png)

There is a lock on it, so it won't proceed anymore.
so I made a boot file after seeing the solution of the other writings you left.
HDR-CX670 can't be unlocked. Could you help me?

**Comment by ma1co** [comment]
Duplicate of https://github.com/ma1co/OpenMemories-Tweak/issues/392.
