### ISSUE TITLE
Loading plugin

### ISSUE THREAD

**Issue by mrjameshamilton** [ma1co/Sony-PMCA-RE#23]
The website log just says "Loading plugin" and doesn't get any further.

**Comment by ma1co** [comment]
Please use Internet Explorer and install the [plugin](https://sony-pmca.appspot.com/plugin/install).

**Comment by mrjameshamilton** [comment]
I installed the plugin and tried internet explorer as well as chrome

**Comment by ma1co** [comment]
Are you sure it was IE and not Edge?

If it doesn't work in the [official Sony app store](https://www.playmemoriescameraapps.com/) either, I can't help.

But you can always try [pmca-gui](https://github.com/ma1co/Sony-PMCA-RE/releases/tag/v0.9).
