### ISSUE TITLE
Sony ZV-1

### ISSUE THREAD

**Issue by kungaa** [ma1co/Sony-PMCA-RE#231]
I am guessing that it would be impossible to add ZV-1 support? I have tried to follow instructions from [DSC-WX500 thread](https://github.com/ma1co/Sony-PMCA-RE/issues/196) but did not get any matches:

```
pmca-console guess_firmware -f 0x51020000.zip
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Model name: ZV-1

Trying 100 firmware images
Fail: No matching file found
```

**Comment by jiferent** [comment]
Did you get it to work?

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
