### ISSUE TITLE
FDR-AX60

### ISSUE THREAD

**Issue by tinhtu2012** [ma1co/Sony-PMCA-RE#238]
@ma1co Would you please add model FDR-AX60 which is Japanese only language. I would like to change to English.
From the specs it is the same as FDR-AX53. Can I use AX53 firmware to upload to AX60?
Thank you.

**Comment by tinhtu2012** [comment]
> @ma1co Would you please add model FDR-AX60 which is Japanese only language. I would like to change to English.
> From the specs it is the same as FDR-AX53. Can I use AX53 firmware to upload to AX60?
> Thank you.

Here is the error
![error](https://user-images.githubusercontent.com/83978164/118035108-a34ca780-b31f-11eb-9257-37b4ede2f6dd.JPG)

**Comment by tinhtu2012** [comment]
I wonder if FDR-AX43 and FDR-AX45 is listed in here

https://github.com/ma1co/Sony-PMCA-RE/tree/master/updatershell/fdat/gen3

then FDR-AX60 should be  in the radar, since they share the same manual:

https://helpguide.sony.net/cam/1720/v1/en/contents/TP0000945876.html

I wish @ma1co look into it. Please help me! Thanks.

**Comment by tinhtu2012** [comment]
I ran the command "pmca-console guess_firmware -f 0x71010000.zip"

it found "Success: Found matching file: gen3_0x71010096_1.dat"

Is there a hope for this Camcorder?
[0x71010000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/6474016/0x71010000.zip)
![FDRX60success](https://user-images.githubusercontent.com/83978164/118161361-5545ab80-b3d4-11eb-83c3-43f315236832.JPG)

**Comment by tinhtu2012** [comment]
Hi Marius,
@undingen Would you please help me? Thank you very much in advance.

**Comment by tinhtu2012** [comment]
Hi @ma1co,

Would you please help me or show me how to do it? If this model cannot be done, please me know too. So I don't hope and wait for it.  Thanks a lot in advance.

**Comment by ma1co** [comment]
Thank you, the FDR-AX60 is now supported in updatershell.

The next step is to dump the firmware. Here's how to do that:

* Download the newest build of pmca-console.
* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by tinhtu2012** [comment]
> Thank you, the FDR-AX60 is now supported in updatershell.
> 
> The next step is to dump the firmware. Here's how to do that:
> 
> * Download the newest build of pmca-console.
> * Connect the camera.
> * Run `pmca-console updatershell`
> * Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
> * Run the following updatershell command to dump the bootloader partitions: `bootloader`
> * Run the following updatershell command to reboot your camera back to normal mode: `exit`
> * You should now have files called `nflasha` and `boot` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).
> 
> Thank you for your help!

@ma1co Thank you very much for your help. I am very glad that you have come back to rescue us. 

I uploaded the files already to your dropbox. For some reason it create 5 boot files. I included them all. Let me know if I have to redo it.

Can I buy you a drink? Do you have Venmo or Paypal?

**Comment by tinhtu2012** [comment]
I just want to copy it here to see what I have done:

C:\Users\sonyPMCA>pmca-console updatershell
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation FDR-AX60 is a camera in MTP mode

Getting device info
Using firmware for model FDR-AX60

Initializing firmware update
Switching to updater mode

Waiting for camera to switch...
Please follow the instructions on the camera screen.
Initializing firmware update
Writing firmware
0%
100%
Starting updater shell...

Welcome to the USB debug shell.
Type `help` for the list of supported commands.
Type `exit` to quit.
>pull /dev/nflasha
Writing to .\nflasha...
0%
5%
10%
15%
20%
25%
30%
35%
40%
45%
50%
55%
60%
65%
70%
75%
80%
85%
90%
95%
100%
>bootloader
Writing to .\boot1...
Writing to .\boot2...
Writing to .\boot3...
Writing to .\boot4...
Writing to .\boot5...
>exit
Done

C:\Users\sonyPMCA>

**Comment by tinhtu2012** [comment]
@ma1co I did ran pull /dev/nflasha before the Tweaks. Is that matter?

**Comment by ma1co** [comment]
All good, thank you for the dump.

**Comment by robouden** [comment]
Sorry for reopening the issue. I got an FDR-AX60 with Japanese and also like to change it to English on a Linux Mint system. I am getting the following error when I try to connect to the camera.

`usb.core.USBError: [Errno 13] Access denied (insufficient permissions)`

Any suggestions?

Regards,
Rob Oudendijk
