### ISSUE TITLE
HDR-CX170

### ISSUE THREAD

**Issue by SlonoPtah** [ma1co/Sony-PMCA-RE#239]
Hello,

Would it be possible to add HDR-CX170 japanese only Cam so that I can change the language to some normal one?
This is info with pmca-console guess_firmware -f 0x31020000.zip:

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Getting device info
Model name: HDR-CX170

Trying 100 firmware images
Firmware update error: Invalid data
Success: Found matching file: gen2_0x31020000_0.dat

Thank you in advance!

**Comment by ma1co** [comment]
The firmware of the HDR-CX170 is most likely similar to the one of the [HDR-XR550V](https://github.com/ma1co/OpenMemories-Tweak/issues/265). These models are currently not supported.

**Comment by ma1co** [comment]
I have just posted some instructions in the [linked issue](https://github.com/ma1co/OpenMemories-Tweak/issues/265). If you want to help, please continue the discussion there.
