### ISSUE TITLE
A6000 firmware cannot be upgraded.

### ISSUE THREAD

**Issue by a997476356** [ma1co/Sony-PMCA-RE#24]
My English is not very good. This is using Bing translator.
  A6000 firmware cannot be upgraded. I am using is "PMCA-console-v0.10-win firmware-f FirmwareData_ILCE6000V320.dat". Error message:

E:\BaiduYunDownload\sonyapp>pmca-console-v0.10-win firmware -f FirmwareData_ILCE6000V320.dat
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Initializing firmware update
Traceback (most recent call last):
  File "<string>", line 67, in <module>
  File "<string>", line 61, in main
  File "pmca\commands\usb.py", line 254, in firmwareUpdateCommand
  File "pmca\usb\sony.py", line 319, in checkGuard
  File "pmca\usb\sony.py", line 296, in _sendWriteCommands
Exception: Firmware update error: Invalid version
pmca-console returned -1

![image](https://cloud.githubusercontent.com/assets/25764358/22921011/e3cbce24-f2d2-11e6-8e22-fc4d160dfe54.png)

Use your Sony-PMCA-RE,mtp mode mass storage mode and tried everything also cannot be updated.

**Comment by ma1co** [comment]
That is normal. You can't install the same firmware update multiple times.

**Comment by mturkdfeldt91** [comment]
@ma1co How do we restore the system to new if you can't update and something goes wrong?
