### ISSUE TITLE
Sony A7III & 30 Min. limit

### ISSUE THREAD

**Issue by David-tech-2021** [ma1co/Sony-PMCA-RE#241]
Hello knowledgeable people.
I don't manage to install the OpenMemories tweak on my Sony A7III after the camera was identified, instead I get promptly this message:
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

Any suggestions will be welcomed! 

Many thanks
David

**Comment by denver009** [comment]
HI CAN ANY ONE PUT SUPPORT FOR OLD ALPHA 68 CAMERA IN PMCA GUI..
SINCE IT IS NOT SUPPORTED..

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
