### ISSUE TITLE
Sony Nex-F3

### ISSUE THREAD

**Issue by hypnotoad64** [ma1co/Sony-PMCA-RE#244]
Hi Everyone,
I'm trying to install the OpenMemories: Tweak onto my Sony NEX-F3 but I'm getting an error code.
`InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0`
I've already tried running the command line: `pmca-console guess_firmware -f 0x21020000.zip` that some users suggested in similar posts, but it failed to ID the model of the camera.
I was hoping to find out what the issue was. I was able to use the "Tweaks" in the pmca-gui but I wanted to use the OpenMemories: Tweak in order to access the command line interface to unlock the clean HDMI output. 
I would appreciate any help you all can offer. Thanks!
Here is the camera info that shows up in the pmca-gui in case that helps:
`Model:              NEX-F3
Product code:       0032821815
Serial number:      01111330
Firmware version:   1.01`

**Comment by ma1co** [comment]
The NEX-F3 does not support apps, so you cannot install OpenMemories: Tweak. But you should be able to make the same changes through `pmca-console updatershell`.
