### ISSUE TITLE
HDR-CX700v (Japanese version) Language change.

### ISSUE THREAD

**Issue by Akila3** [ma1co/Sony-PMCA-RE#253]
I have an Issue that I have Sony camcorder HDR-CX700V and it seems it is a Japanese version/brand cameras (as i got it on eBay from a dude in Japan) and I want it to change it's language from Japanese to English, couldn't find anywhere to do so and I suspect they don't have that Option available in the setup menu.
Right now I want to change my Sony HDR-CX700V from Japanese to the English language.
Please help me with this, I believe that you can do this, else please refer me a good solution, if you know of any.
P.S. I also uploaded to your Dropbox my Camera Dump "HDR-CX700V.rar"

**tried few:** 
0x31010000.zip
0x41010000.zip
0x51010000.zip
from different posts I found you instructed them to use

------

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Getting device info
Model name: HDR-CX700V

Trying 100 firmware images
Fail: No matching file found

--My Camera Info from GUI--
Model:              HDR-CX700V
Product code:       0002091301
Serial number:      00023441
Firmware version:   1.00
GPS Data:           2018-01-06 00:00:00 - 2018-02-05 00:00:00

**Comment by ma1co** [comment]
Please try the newest [development builds](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).
