### ISSUE TITLE
Again, the HX200V is supported in updatershell / pmca-gui through the "Tweaks" tab.

### ISSUE THREAD

**Issue by TITAN5000** [ma1co/Sony-PMCA-RE#254]
Again, the HX200V is supported in updatershell / pmca-gui through the "Tweaks" tab.

_Originally posted by @ma1co in https://github.com/ma1co/Sony-PMCA-RE/issues/146#issuecomment-897501859_

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Using firmware for model DSC-HX200V

Unknown device: DSC-HX200V

there is no result, it is not stitched

**Comment by ma1co** [comment]
Please use the [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts)
