### ISSUE TITLE
sony-pmca.appspot.com Server Error

### ISSUE THREAD

**Issue by sceic** [ma1co/Sony-PMCA-RE#259]
Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.

**Comment by KociolekPL** [comment]
This problem also occurred in my case. Error 500 lasts for one week straight. Is this a reason why I cannot download "OpenMemories: Tweak" and install clean-HDMI output on my alfa5000?

**Comment by ma1co** [comment]
The browser plugin method is not supported anymore. Please use the binaries instead.
