### ISSUE TITLE
Looking for Sony devices: operation timed out

### ISSUE THREAD

**Issue by colsub10** [ma1co/Sony-PMCA-RE#26]
Hi, here https://www.youtube.com/watch?v=Bj3txJ9zVnY  you can see my problem:"Looking for Sony devices: operation timed out" :( 
The 0.10 version GUI recognizes my camera Sony A7m2, then I load OpenMemories-Tweak.apk, the program reboot camera...but while the camera will restart the program gives me this error: "Exception: Timeout". 
My camera is set to MPT and SINGLE LUN USB.
Can someone help me ? Thanks :)

**Comment by ma1co** [comment]
Does your camera show the "Application Download" screen after switching?

Does the official app store work for you?

**Comment by colsub10** [comment]
Thanks for reply.

No, after every reboot my camera shows the screen "USB Connection MTP".
Here a short video https://youtu.be/QOWPoovnIFw?list=PLJAlQaKQ1_wTW_ahGjRM8jYPCfK-hydLc

No, via the official website https://www.playmemoriescameraapps.com/portal/ I can not download apps from the web site to my camera :(
Always appears a window that says "Check Connection in progress ..." the camera restarts end ... :(
I tried it on two Macs with Yosemite and 2 PCs with Windows 10 latest version: same result is using the PMCA-gui is the official site is this https://sony-pmca.appspot.com/plugin site.
In camera I installed some free app connecting via wifi from the camera.

For my work I need to eliminate the limit of 30 minutes!
Please help :)

**Comment by ma1co** [comment]
That black screen looks like a crash to me... Are you using the USB cable that came with the camera (this seems to be pretty important)?

If you can't get the offcial app store to work, I can't really help you...

**Comment by colsub10** [comment]
Thanks for reply.

I have always used different usb cables, never his in the box.
Today I tried using the small original usb cable ... same result.
The room will restart and that's it :(

I would try to initialize the room and then make a test... but is where a way to save the profile settings of menu ?
I would not go into the menu and change everything to return as before.

Thanks ;-)
