### ISSUE TITLE
Not being able to install apps on A7 III. I only managed to make it work on my A7s.

### ISSUE THREAD

**Issue by CrookedDrook** [ma1co/Sony-PMCA-RE#260]
Loading app list
Cannot connect to remote server, falling back to appstore repository
Found 11 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-7M3 is a camera in MTP mode

Model:              ILCE-7M3
Product code:       0032829530
Serial number:      03804381
Firmware version:   4.01
Lens:               Model 0x13a0801b (Firmware 1.02)

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

I tried doing it with and without the MTP mode but it didn't work regardless, i have 2 A7 III cameras and would love to save myself trouble by unlocking the 30m limit, thanks in advance for your help.

Querying MTP device
Sony Corporation ILCE-7M3 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "pmca-gui.py", line 75, in do
  File "pmca\commands\usb.py", line 286, in installCommand
  File "pmca\commands\usb.py", line 34, in switchToAppInstaller
  File "pmca\usb\sony.py", line 338, in switchToAppInstaller
  File "pmca\usb\sony.py", line 276, in _sendCommand
  File "pmca\usb\sony.py", line 130, in sendSonyExtCommand
  File "pmca\usb\__init__.py", line 86, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006

**Comment by DarCoF** [comment]
Exact same issue happening for my sony alpha 7III. The camera is able to connecto in MTP mode. But when running the gui console this message shows up: "Loading app list
Cannot connect to remote server, falling back to appstore repository
Found 11 apps".
Then, when trying to install "Openmemories Tweak" app I am running against the same MPT 0x2006 error.

I am trying to unlock all language options since my camera is currently in chinese (not really helpful) so I bit of help would be appreciated. Is there any other workaround? Like a comple wipe out of the current firmware and installation of a new one. It sounds risky thou.

Thanks for any help.

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).

**Comment by VVitay** [comment]
Thanks for advance, where i can see that a7m3 now in supported list?
 
 
----------------------------------------------------------------------
С уважением,
Виктор Ваньков.

**Comment by ma1co** [comment]
Good point. I added it here: https://openmemories.readthedocs.io/devices.html Probable needs another column for service mode...

**Comment by SirLeeleo** [comment]
Hi there Ma1co.
been following your posts and I've been trying to take the 30 minute limit on my Sony A7m3, but when I run the app it says that my device does not support apps, just like some of the users here. my camera is the version ILCE 7M3 with firmware version 4.03.

excuse me for being so all over the place, but I am new to all this and I would love some assistance on how to do this. i downloaded both the console and GUI V0.18.

**Comment by SirLeeleo** [comment]
> Good point. I added it here: https://openmemories.readthedocs.io/devices.html Probable needs another column for service mode...

Hi there Ma1co.
been following your posts and I've been trying to take the 30 minute limit on my Sony A7m3, but when I run the app it says that my device does not support apps, just like some of the users here. my camera is the version ILCE 7M3 with firmware version 4.03.

excuse me for being so all over the place, but I am new to all this and I would love some assistance on how to do this. i downloaded both the console and GUI V0.18.

**Comment by kjustin2222** [comment]
guys, I think this camera can't work in multiple languages I mean sony a7iii

**Comment by waurengee** [comment]
I have the same issue unable to install with my Sony A7iii:
ILCE 7M3 firmware version 4.01
PMCA-GUI V0.18.
-------------------------------------------------------
Querying MTP device
Sony Corporation ILCE-7M3 is a camera in MTP mode

Switching to app install mode
Error: This device does not support apps

**Comment by Tomoti007** [comment]
> ## У меня такая же проблема, которую невозможно установить на моем Sony A7iii:
> версия прошивки ILCE 7M3 4.01
> PMCA-GUI V0.18.
> Запрос устройства MTP Sony Corporation ILCE-7M3 - это камера в режиме MTP
> 
> Ошибка переключения в режим установки приложений: это устройство не поддерживает приложения

Добрый вечер! Разобрался с ошибкой. Надо было с MTP переключить в USB Mass Store и желательно взять кабель с телефона который 100% передает данные, а дальше по инструкции которое на видео: https://www.youtube.com/watch?v=82A_SxMjtc0 и обязательно файлы которые я прикреплю. В архиве самое свежие версии pmca-console и gui потому что с более старыми версиями не получалось. Итог: получилось снять ограничения записи в 30 минут и установить языковой пакет.
[Downloads.zip](https://github.com/ma1co/Sony-PMCA-RE/files/13440661/Downloads.zip)


> ## I have the same issue unable to install with my Sony A7iii:
> ILCE 7M3 firmware version 4.01
> PMCA-GUI V0.18.
> Querying MTP device Sony Corporation ILCE-7M3 is a camera in MTP mode
> 
> Switching to app install mode Error: This device does not support apps

Добрый вечер! Разобрался с ошибкой. Надо было с MTP переключить в USB Mass Store и желательно взять кабель с телефона который 100% передает данные, а дальше по инструкции которое на видео: https://www.youtube.com/watch?v=82A_SxMjtc0 и обязательно файлы которые я прикреплю. В архиве самое свежие версии pmca-console и gui потому что с более старыми версиями не получалось. Итог: получилось снять ограничения записи в 30 минут и установить языковой пакет.
[Downloads.zip](https://github.com/ma1co/Sony-PMCA-RE/files/13440661/Downloads.zip)
