### ISSUE TITLE
HDR-CX240

### ISSUE THREAD

**Issue by dicamarques14** [ma1co/Sony-PMCA-RE#264]
Is it possible to support the HDR-CX240?
Anything I can do to help support this model? I want to toggle a PAL to NTSC

**Comment by ma1co** [comment]
First, we have brute force the model id of your camera. Here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
* Download [0x41010000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/2928160/0x41010000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x41010000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by dicamarques14** [comment]
Match found

`Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Getting device info
Model name: HDR-CX240E

Trying 100 firmware images
Firmware update error: Invalid region
Success: Found matching file: gen3_0x41010016_1.dat`

**Comment by ma1co** [comment]
Thank you, the HDR-CX240 is now supported in updatershell. Here is how to dump the firmware:

* Download the newest [build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts) of pmca-console.
* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by dicamarques14** [comment]
Just uploaded the zip.
Thank you

**Comment by dicamarques14** [comment]
Sorry to bump, but is there any update?

**Comment by ma1co** [comment]
Thank you for the dump. The camera should already be supported in pmca-console and pmca-gui.
