### ISSUE TITLE
pmca-console market Login fail

### ISSUE THREAD

**Issue by NetrunnerAT** [ma1co/Sony-PMCA-RE#27]
Greetings from Austria!

Python run time runs if i use pmca-console info

If i use pmca-console market and put in my user and pw, i get every time Login fail!

I have try win7 and win10, with python3.6 or not and two different accounds. i doesnt get error messages. I have try pmca-console 0.7 to 0.10!

**Comment by ma1co** [comment]
Yes, the login doesn't work anymore since Sony added the recaptcha. Use your browser to log into the app store, copy the _portalid_ cookie and run `pmca-console market -t <your_portalid_here>`.
