### ISSUE TITLE
STG Uploader & Videos

### ISSUE THREAD

**Issue by andfay** [ma1co/Sony-PMCA-RE#28]
Hi, Works brilliantly with a couple of exceptions.  
1. All photos are uploaded but videos do not work from my camera.
Camera is HX90V set to AVCHD and the .mts file appears in Google photos as a grey box with the message "Your video will be ready soon" but it never is.
I downloaded the video from camera to PC into a folder that Google Photos backs up and it worked fine so I don't think it is a Google issue.
I was testing with small files sizes about 8-12 MB each.
2. Uploaded all photos and a couple of videos via STG then deleted the videos numbered 00000 and 00001from the camera and from Google. 
Recorded new videos but 00000 and 00001 would not upload as they were presumably still in the database from before.  00002 and above worked and clearing the database caused all to be uploaded.  Is there any other way around this?

**Comment by ma1co** [comment]
This is something @Bostwickenator has to look at. I'll close the issue because this is the wrong repo.

**Comment by Bostwickenator** [comment]
Apologies for that @ma1co. To avoid future confusion I just setup a stub repo for STG uploader @andfay please submit this issue here https://github.com/Bostwickenator/STGUploader
