### ISSUE TITLE
Cannot conenct to remote server

### ISSUE THREAD

**Issue by marioos7** [ma1co/Sony-PMCA-RE#286]
the pmca-gui v0.17 starts with an error 
Cannot connect to remote server, falling back to appstore repository

<img width="760" alt="Screenshot 2022-02-16 at 18 26 03" src="https://user-images.githubusercontent.com/99824251/154310408-51599d08-4605-4e40-bda0-2426bb837977.png">
<img width="443" alt="Screenshot 2022-02-16 at 18 26 54" src="https://user-images.githubusercontent.com/99824251/154310564-39fd95ae-aa7f-458b-8a5f-f2950b460527.png">

**Comment by ma1co** [comment]
Should be fixed with a8abd1b692c41392e0c9582915779d8a188edce8
