### ISSUE TITLE
sony ZV-E10 please  add language support 

### ISSUE THREAD

**Issue by ajayravi143** [ma1co/Sony-PMCA-RE#290]
sony ZV-E10 please  add language support 
it says unknown device
the camera is out of stock everywhere
i could only get Japanese version but cant use it.

Getting device info
Using firmware for model ZV-E10

Unknown device: ZV-E10

Loading app list
Cannot connect to remote server, falling back to appstore repository
Found 11 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

**Comment by omgitsbillryan** [comment]
I'm in the same boat as you. I think this camera has some kind of language lock due to regional licenses.

**Comment by Matvienkoilia** [comment]
Yes, would be helpful. Getting the same error. Although with the latest build got "Error: This device does not support apps" - not sure if it is correct error. Or if there is any other way around.

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).

**Comment by dazhbog** [comment]
Im having an error with ZVE10

```
PS C:\Users\XXXX\Downloads> C:\Users\XXXX\Downloads\pmca-console-v0.18-9-g2590782-win.exe serviceshell
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to service mode

Waiting for camera to switch...
Found a camera in service mode
Authenticating
Starting service shell...

Welcome to platform shell.
Type `help` for the list of supported commands.
Type `exit` to quit.
>help
List of supported commands:
 help                    Print this help message
 exit                    Exit
 info                    Print device info
 tweak                   Tweak device settings
 shell                   Start an interactive shell
 push <LOCAL> <REMOTE>   Copy the specified file from the computer to the device
 pull <REMOTE> [<LOCAL>] Copy the specified file from the device to the computer
 bootrom [<OUTDIR>]      Dump the boot rom
 bk r <ID>               Read backup property
 bk w <ID> <DATA>        Write backup property
 bk s                    Sync backup data to disk
 bk lock                 Lock protected backup settings
 bk unlock               Unlock protected backup settings
>tweak
1: [X] Disable video recording limit
       13h 01m 00s

2: [ ] Unlock all languages
       7 / 35 languages activated

3: [X] Enable PAL / NTSC selector & warning
       Enabled

4: [X] Enable USB app installer
       Enabled

5: [ ] Unlock protected settings
       Protection enabled

Enter number of tweak to toggle (0 to finish): 2
Error: Senser adjust control error 129
```

And by using the GUI I also get this
<img width="701" alt="image" src="https://user-images.githubusercontent.com/1836262/174783131-3443d9ea-1d6c-4448-a5bc-b275c4113ca2.png">

Any ideas? ZV-E10 V2.00

**Comment by dazhbog** [comment]
OK problem solved. Have to check "unlock protected settings" first. Then Unlock languages! Works yay!

**Comment by MyN678** [comment]
> In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).

Dear dazhbog, mac1co
I'm a new guy come. Could you please guide me how to use "development build" method.
I'm struckling with my sony zv-e10. I just know how to use GUI in window (.exe file)
thank you

**Comment by WynnterPixel** [comment]
![Screenshot 2022-10-07 011741](https://user-images.githubusercontent.com/115178381/194377489-60164042-8c23-4661-a4a8-26493996988f.jpg)
I dont have the TWEAK option, Am I doing something wrong?
ZVE10 Firmware 2.0 Japanese Variant.

Hoping for anyone's assintance. TY

**Comment by WynnterPixel** [comment]
![Screenshot 2022-10-07 011741](https://user-images.githubusercontent.com/115178381/194378208-c8ff9956-ac89-41b2-8d44-8fae9fdd7e61.jpg)
I dont have the TWEAK option, Am I doing something wrong?

ZVE10 firmware 2.0 Japan Variant

 thanks

**Comment by dazhbog** [comment]
Yes you are right @MyN678 I also cant find the artifacts from the development build. Maybe @ma1co can shine some light.

I found them on my PC, this is what i used for my ZV-E10. **Use at your own risk and don't click random things**

[pmca 18-9.zip](https://github.com/ma1co/Sony-PMCA-RE/files/9730710/pmca.18-9.zip)

Follow my comments above to do it. Put camera in serviceshell >> unlock protected settings >> Unlock languages!

**Comment by MyN678** [comment]
thank you for your help.

**Comment by WynnterPixel** [comment]
Hi! i too have the same problem
I checked unlock protected settings first. but it wont toggle as marked

**Comment by dazhbog** [comment]
Please list versions, logs and all these things. Help us help you!

**Comment by WynnterPixel** [comment]
![1](https://user-images.githubusercontent.com/115178381/194496281-5e8af366-4941-47ce-a341-0e07a22675da.png)
![2](https://user-images.githubusercontent.com/115178381/194496295-6a0ffe98-ba7c-45bd-891d-bad9fa8936ef.png)
![3](https://user-images.githubusercontent.com/115178381/194496386-17f1d393-11c2-4d8a-8435-dba408fd8d9d.png)
![4](https://user-images.githubusercontent.com/115178381/194496405-4d8b9fda-1a6c-47ae-9a52-c7343117f4d9.png)

I'm new into this things. I'm not familiar with logs. but this is what I've been encountering. sorry

**Comment by dazhbog** [comment]
Hmmm, did you use Zadig after the camera has switched to serviceshell? You need to install drivers for both mass storage and serviceshell modes.

https://github.com/ma1co/Sony-PMCA-RE#service-mode

**Comment by MyN678** [comment]
For mine:
1.plug my zve10 to pc on mass storage
2. run Zadig to change my ZV-E10 to libusb-win32 (v1.2.6.0)
3. using powershell I ran pmca-console-v0.18-9-g2590782-win.exe serviceshell
4. run Zadig to change Sony USB to libusb-win32 (v1.2.6.0) --> Zdiag hang can't install driver
![image](https://user-images.githubusercontent.com/114942635/194559673-ec2490c6-ddf7-40ad-9b6e-7e29e4d8183a.png)

**Comment by WynnterPixel** [comment]
removed my comment. I'm an idiot with low reading comprehension. I have to install drivers on Sony USB device
 @MyN678  that's what I'm doing now. and Yes, mine aborted aswell

**Comment by dazhbog** [comment]
Try:
- Run Zadig as admin. and try it a few times. 
- Maybe you need to close the terminal that uses the driver. 
-  Keep the device manager open to see what is happening while the drivers install

**Comment by MyN678** [comment]
I think Sony USB is installed driver successfully 
![image](https://user-images.githubusercontent.com/114942635/194561182-8d55db0c-d2b8-49ff-86dd-5ce50fcddd86.png)
but can't active remove protect settings.

**Comment by WynnterPixel** [comment]
@MyN678 @dazhbog 
Happens to me aswell.

1.plug zve10
2.run Zadig , replace driver to libusb-win32 (v1.2.6.0) on ZV-e10
3.run pmca-console-v0.18-9-g2590782-win.exe serviceshell on powershell
4. tried to install driver libusb-win32 (v1.2.6.0) on  Sony USB device, Zadig aborted installation, Repeat several time on Run as admin and closed terminal. Zadig crashed and aborted driver installation.
5. skip 4
6. enter help>tweak> can't toggle Unlock protection and/or Unlock all languages

Are Japanese Variants really that Hardcore region locked? or I'm really doing something wrong here.

**Comment by wetsoba** [comment]
Any luck with this?

**Comment by D-RAJ65** [comment]
I followed along with all the steps in this thread (on my Sony ZV-1) on a **Windows** machine and encountered all the same problems. I was unable to "Unlock protected settings" or "Unlock all languages" (I also got the Error: Senser adjust control error 129).

I was ready to give up and decided to give it one last try from my **Linux** desktop and **it worked the first time**. I was able to enable 35/35 languages! It was super simple....wish I had tried the Linux version first. No need to mess around with Zadig drivers either.

If you do install the Linux version, you may also need to run "sudo apt install python3-tk" to install an additional driver not included in the requirements file.

**Comment by MyN678** [comment]
Hi @D-RAJ65 

It's great help. I try with trial Untubu and get success with my ZV-E10
Thank you so much bro

**Comment by D-RAJ65** [comment]
That's great! I made a Youtube video as well to help others facing this same issue.

[https://www.youtube.com/watch?v=06x0_Edrph8](https://www.youtube.com/watch?v=06x0_Edrph8)

**Comment by SadJapanese** [comment]
@dazhbog Hi did you do this on windows?

@D-RAJ65 Do you have a solution using it in windows? I don't have other OS :(

**Comment by D-RAJ65** [comment]
@SadJapanese Windows was hit and miss. Worked for some but not for me. Linux worked instantly.

You can run Linux one time on your computer (without installing it) just to do the unlock. Watch my Youtube video above. I show you how you can download and run Linux Mint on your computer so that you can run the Linux version of this software to unlock your camera. Then you can reboot your machine back into Windows.

I was able to do this with a ZV-1 and another user commented it worked for their ZV-E10.

**Comment by SadJapanese** [comment]
![Untitled](https://user-images.githubusercontent.com/119785773/227280967-604c1ad1-5edb-442b-9a58-0f74498b92c0.png)
I tried using linux but whenever I get camera info this happens.
@D-RAJ65

**Comment by subzeroxp** [comment]
> ![Untitled](https://user-images.githubusercontent.com/119785773/227280967-604c1ad1-5edb-442b-9a58-0f74498b92c0.png) I tried using linux but whenever I get camera info this happens. @D-RAJ65

did you manage to solve?
I have exactly this problem

**Comment by D-RAJ65** [comment]
@subzeroxp @SadJapanese Try running the program with elevated privileges using "sudo ./pmca-gui.py".

Also unplug and replug the USB cable in after running this command.

**Comment by D-RAJ65** [comment]
A few people reported this " Access denied: insufficient permissions" error to me, so I gave it another go. Although I was able to successfully use this method on my computer running with Linux **installed**, it unfortunately does not seem to work when _booting_ Linux off a USB drive.

If you have a spare / old computer lying around, you can install Linux on it and then this method will work. I just tested it again on my computer and it worked instantly just like in my Youtube video.

**Comment by Erur0su** [comment]
Guys, anyone managed to solve the 129 error issue? got myself zv-e10 for 530 bucks in japan. But i just cant get through it. Console somehow would launch and close itself in a matter of sec so i turned to "gui" version. It makes everything go till Error 129 appears when i try to unlock languages. If i try to unlock protected settings nothing happens. I am far from being a tech guy. Pls help the dumbie :(

**Comment by Erur0su** [comment]
Hey everyone!
Anyone managed to solve things for windows? I got exactly same error.
Pls find below the things i get when i try to go directly for enabling languages as hitting protection button just does nothing to my camera. Hope you can help me.
![sonyprtscrn](https://github.com/ma1co/Sony-PMCA-RE/assets/153851448/889267bb-87e3-4bd2-a19d-c9431afcf84e)

**Comment by Belimix** [comment]
Guys, please tell me. I want to update the driver in Zadig, but my original one is not the same as everyone else's. What to do? Where to look?
![image](https://github.com/ma1co/Sony-PMCA-RE/assets/72004994/bcb2a245-c25d-4fdd-856a-c85969f000e7)
