### ISSUE TITLE
Want to enable multiple language support for Sony RX100M7

### ISSUE THREAD

**Issue by nitinbarve** [ma1co/Sony-PMCA-RE#295]
hi,  
can you help to guide me procedure to enable multiple language support for my Sony RX100M7 
currently stuck with Japanese language only. Your help will be greatly appreciated. 

I researched  a lot online about it and found this Forum to be Legit thus joined in here to get/ask for help.
![20220326_222800](https://user-images.githubusercontent.com/102422595/160244176-0116af89-ccc6-4376-ae14-daa1aa7b69a7.jpg)

i tried pmca-gui-v0.17-osx.dmg but get attaached MTP error.

**Comment by nitinbarve** [comment]
Thanks to wanghaixian1995@gmail.com on this forum.
With his help i was able to enable SONY RX100M7 all language settings. :)

**Comment by nitinbarve** [comment]
Thanks to wanghaixian1995@gmail.com
With his help i was able to enable SONY RX100M7 all language settings. :)

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).

If you manage to run it, I would be interested in a firmware dump. You can dump the firmware using `pull /dev/nflashaB0` and `pull /dev/nflasha` in serviceshell. Please upload the files to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx). Thanks!
