### ISSUE TITLE
Support Sony ILCE-6600

### ISSUE THREAD

**Issue by stultusverus** [ma1co/Sony-PMCA-RE#297]
Since ILCE-6000, 6300 and 6500 are all supported, perhaps it is also possible to support 6600?

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
