### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by raminolta** [ma1co/Sony-PMCA-RE#30]
Went to install the 'Focus Bracket' app but the site is down (over quota message). I could get the local installer but I need the app installing file (I think it must be an apk pacakge). Does anybody know where to get that one?

**Comment by ma1co** [comment]
The site will be back up in 9 hours.

You can get the apk [here](https://github.com/obs1dium/FocusBracket/releases/latest). However, you have to use pmca-console with the -s parameter if the site is down:

    pmca-console install -s "" -f app.apk

**Comment by raminolta** [comment]
Many thanks for the super fast response. I will wait.

**Comment by raminolta** [comment]
I actually managed to install it through cammand line. It wasn't that comlicated after all.
