### ISSUE TITLE
Cannot install Timelapse App

### ISSUE THREAD

**Issue by Jen2137** [ma1co/Sony-PMCA-RE#301]
Hi!

I wanted to install the timelapse app but I have encountered some issues. Could anyone help me with that? Below I attached the whole message from the PMCA-GUI, the latest 0.18 version.

Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6000 is a camera in app install mode

Traceback (most recent call last):
  File "pmca-gui.py", line 75, in do
    installCommand(appPackage=app.package)
  File "pmca\commands\usb.py", line 300, in installCommand
    installApp(device, apkFile, appPackage, outFile)
  File "pmca\commands\usb.py", line 48, in installApp
    with ServerContext(LocalMarketServer(certFile)) as server:
  File "pmca\marketserver\server.py", line 42, in __init__
    HTTPServer.__init__(self, (host, port), HttpHandler)
  File "socketserver.py", line 456, in __init__
  File "http\server.py", line 138, in server_bind
  File "socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 1: invalid continuation byte

**Comment by Jen2137** [comment]
I found the solution. It turned out that my computer name had one Polish symbol in it, "ę". Changing the name using the English alphabet resolved the problem.

**Comment by ma1co** [comment]
This should be fixed with 01a6df32086c4e486a9562fd42762f87c6ef0f3e.
