### ISSUE TITLE
Clean HDMI for DSC-HX200V

### ISSUE THREAD

**Issue by bactac** [ma1co/Sony-PMCA-RE#313]
I bought a cheap used DSC-HX200V for streaming as it had 1080p60, but as many of you who ended up here, this camera lacked clean HDMI output because of an [annoying "0EV" exposure value indicator](https://imgur.com/a/vo9gCCO).

Reading up [Clean HDMI out for a5000](https://github.com/ma1co/OpenMemories-Tweak/issues/70) and seeing how everything was boiled down to finding a key whose value had to be set from 01 to 00, I decided to try finding this key for the DSC-HX200V. 

The key to be set to 00 is `0x01070330`, so all steps to clean HDMI for this camera are:

1. Plug camera on USB and turn it on
2. Run `pmca-console updatershell`
3. Press OK (middle menu button) so the camera restarts in updater mode. Wait a few seconds. If everything went fine, you'll be welcomed with "Welcome to the USB debug shell" on your terminal. If it says it is isted as a camera in updater mode but cannot get the camera model, try again with `pmca-console updatershell -m DSC-HX200V`. If it gives an exception about low battery, plug the DC adapter and retry. To return to normal camera mode, reinsert the battery.
4. Enter the following commands: 
```
bk w 0x01070330 00
bk s
exit
```
5. Camera will return to normal mode after the `exit` command and EV will be gone from the movie mode display
6. To revert back, follow all the steps but set the value from 00 to 01 as in: `bk w 0x01070330 01`

The steps to find the `0x01070330` key were:

1. Get in the USB debug shell of the camera in updater mode (step 3 of the forementioned procedure)
2. Dump the Backup.bin file with `pull /setting/Backup.bin`
3. Decode the Backup.bin file with [fwtool.py](https://github.com/ma1co/fwtool.py) 
4. The generated file will have about 11k keys with their sizes and `attr` which I have no idea what means atm:
```
...
id=0x01070867, size=0x0001, attr=0x01:
  00                                               .

id=0x01070868, size=0x0002, attr=0x40:
  00 00                                            ..

id=0x01070869, size=0x0001, attr=0x01:
  00                                               .

id=0x0107086a, size=0x0004, attr=0xc0:
  00 00 00 00                                      ....

id=0x0107086b, size=0x0004, attr=0xc0:
  00 00 00 00                                      ....
...
```
5. Filter the results with `id=0x0107xxxx`, `size=0x0001` and value of `01`, which will boil them down to about 220 of them.
6. Set them all to 00 with by entering a bunch of `bk w 0x0107xxxx 00` commands. Then `exit` to return the camera to normal mode. Powered it on movie mode and EV is gone (I really didn't pay attention if other weird stuff was happening). So this meant the key was there. If nothing happened I'd probably have given up by there.
7. To isolate the exact key I restored all keys back to `01` and tried setting half of them to `00`. If EV disappeared it meant the key was among that half. Then I kept repeating that process until arriving at `0x01070330`.

The choice of `id=0x0107xxxx`, `size=0x0001` and `attr=0x01` was a guess based on the forementioned answer and I was just lucky that that worked. There is no guarantee that for other cameras this will also be the case.

**Comment by bactac** [comment]
Side note: setting this key to 00 will also lock down the exposure on video mode to 0EV. I haven't found yet anything that could be used to make the EV thing functional but just invisible on the HDMI output...

**Comment by jredoules** [comment]
@bactac Thanks for this procedure. I have been able to remove the EV exposure indicator :)

However, did you find a way to remove the **Scene Recognition Icons** at upper left (tripod in my example) : 
![image](https://user-images.githubusercontent.com/28092379/180750236-3a880eb9-d5a1-4c57-b7bc-d085330d2976.png)

**Comment by bactac** [comment]
> @bactac Thanks for this procedure. I have been able to remove the EV exposure indicator :)
> 
> However, did you find a way to remove the **Scene Recognition Icons** at upper left (tripod in my example)

@jredoules [jredoules](https://github.com/jredoules) Try changing the "Movie shooting scene" option in the menu from "Intelligent Auto" to "Scene Selection"

**Comment by jredoules** [comment]
It works ! Thank you

**Comment by ofunny** [comment]
> Decode the Backup.bin file with [fwtool.py](https://github.com/ma1co/fwtool.py)

~~How did you decode the Backup.bin? I connected via service shell to a SLT a58, dumped the Backup.bin and than tried to decode it via [fwtool.py](https://github.com/ma1co/fwtool.py) what posted "Exception: unknown file type"~~

Took a closer look on [fwtool.py](https://github.com/ma1co/fwtool.py) and found 

>  A Windows firmware updater executable (.exe file)
>   The FirmwareData.dat file extracted from an updater
>   A firmware dump created by running dd if=/dev/nflasha of=dump.dat on the camera

~~So actually it does not support the Backup file type, but can unpack firmware in general. So I would like to ask – how did you get your key file?~~

**Comment by ofunny** [comment]
> > Decode the Backup.bin file with [fwtool.py](https://github.com/ma1co/fwtool.py)
> 
> How did you decode the Backup.bin? I connected via service shell to a SLT a58, dumped the Backup.bin and than tried to decode it via [fwtool.py](https://github.com/ma1co/fwtool.py) what posted "Exception: unknown file type"

Never mind, just checked the commits and the Backup.bin parser has been moved to the pcma-console (https://github.com/ma1co/fwtool.py/commit/a60d85a4cfa7262613613b964efe20a6f5c43da0) so it is no longer part of the [fwtool.py](https://github.com/ma1co/fwtool.py)

**Comment by ofunny** [comment]
> > Decode the Backup.bin file with [fwtool.py](https://github.com/ma1co/fwtool.py)
> 
> How did you decode the Backup.bin? I connected via service shell to a SLT a58, dumped the Backup.bin and than tried to decode it via [fwtool.py](https://github.com/ma1co/fwtool.py) what posted "Exception: unknown file type"

Never mind, just checked the commits and the Backup.bin parser has been moved to the pcma-console (https://github.com/ma1co/fwtool.py/commit/a60d85a4cfa7262613613b964efe20a6f5c43da0) so it is no longer part of the [fwtool.py](https://github.com/ma1co/fwtool.py)

Now the backup parser is located here: https://github.com/ma1co/Sony-PMCA-RE/commit/3bf0e638e24c078462b42ac15ec002fff4e5da95

**Comment by acadeaua** [comment]
when starting the shell after the first command I got
>bk w 0x01070330 00
Error: Protection enabled

any ideas ?
thanks

**Comment by acadeaua** [comment]
> when starting the shell after the first command I got
> 
> > bk w 0x01070330 00
> > Error: Protection enabled
> 
> any ideas ? thanks

found it.
after starting the updatershell, first command to execute:
>tweak

and then, option 4: Unlock protected settings
and then option 0 - to finish

afterwards the initial command to hide the EV will be accepted successfully.

**Comment by eriksonssilva** [comment]
> > > Decode the Backup.bin file with [fwtool.py](https://github.com/ma1co/fwtool.py)
> > 
> > 
> > How did you decode the Backup.bin? I connected via service shell to a SLT a58, dumped the Backup.bin and than tried to decode it via [fwtool.py](https://github.com/ma1co/fwtool.py) what posted "Exception: unknown file type"
> 
> Never mind, just checked the commits and the Backup.bin parser has been moved to the pcma-console ([ma1co/fwtool.py@a60d85a](https://github.com/ma1co/fwtool.py/commit/a60d85a4cfa7262613613b964efe20a6f5c43da0)) so it is no longer part of the [fwtool.py](https://github.com/ma1co/fwtool.py)
> 
> Now the backup parser is located here: [3bf0e63](https://github.com/ma1co/Sony-PMCA-RE/commit/3bf0e638e24c078462b42ac15ec002fff4e5da95)


@ofunny Could you elaborate on how you've been able using it?
I have tried many ways but no matter what I do, I can't parse my backup.bin...
Thanks a lot!

**Comment by AngeloOliveiraTech** [comment]
Please.
How to clean HDMO output when get lenses zoom, appears Zoom Info Wide-Tele.
Whick key is this?

Thanks.
