### ISSUE TITLE
a7iv USB Error on macOS and Linux

### ISSUE THREAD

**Issue by noyhrynban** [ma1co/Sony-PMCA-RE#315]
Currently trying latest (2590782f92575692a881ec588f157b0514b83b7d)
I am needing to unlock the languages on my Japanese a7iv and I am running into the same failure on Mac (12.4 Intel) and Linux (Ubuntu 22) (the stack traces look the same anyway).

> sudo ./pmca-console.py info
> Using drivers OS-X-MSC, libusb-MTP, libusb-vendor-specific
> Looking for Sony devices
> 
> Querying MTP device
> Sony Corporation ILCE-7M4 is a camera in MTP mode
> 
> Traceback (most recent call last):
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/driver/generic/libusb.py", line 85, in write
>     self.dev.write(ep, data)
>   File "/Library/Python/3.8/site-packages/usb/core.py", line 989, in write
>     return fn(
>   File "/Library/Python/3.8/site-packages/usb/backend/libusb1.py", line 837, in bulk_write
>     return self.__write(self.lib.libusb_bulk_transfer,
>   File "/Library/Python/3.8/site-packages/usb/backend/libusb1.py", line 938, in __write
>     _check(retval)
>   File "/Library/Python/3.8/site-packages/usb/backend/libusb1.py", line 604, in _check
>     raise USBError(_strerror(ret), ret, _libusb_errno[ret])
> usb.core.USBError: [Errno 32] Pipe error
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./pmca-console.py", line 99, in <module>
>     main()
>   File "./pmca-console.py", line 65, in main
>     infoCommand(args.driver)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/commands/usb.py", line 246, in infoCommand
>     info = dev.getCameraInfo()
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/sony.py", line 283, in getCameraInfo
>     data = BytesIO(self._sendCommand(self.SONY_CMD_DevInfoSender_GetModelInfo))
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/sony.py", line 272, in _sendCommand
>     data = self.dev.sendSonyExtCommand(cmd[0], (self.ExtCmdHeader.pack(
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/sony.py", line 129, in sendSonyExtCommand
>     response = self.driver.sendWriteCommand(self.PTP_OC_SonyDiExtCmd_write, [cmd], data)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/driver/generic/__init__.py", line 245, in sendWriteCommand
>     self._writePtp(self.TYPE_DATA, code, self.transaction, data)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/driver/generic/__init__.py", line 202, in _writePtp
>     self.write(PtpHeader.pack(
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/driver/generic/__init__.py", line 97, in write
>     self.backend.write(self.epOut[ep], data)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/driver/generic/libusb.py", line 87, in write
>     raise GenericUsbException()
> pmca.usb.driver.generic.GenericUsbException

**Comment by rishabhmhjn** [comment]
@noyhrynban did you find any success?

I have just gotten an A7iv from Japan but with no Language change option! I was wondering if it is possible to change to English?

**Comment by AntoineFacq** [comment]
Hello @rishabhmhjn same for me, did you find any clue to get it to english? #321 seem to show that it is not possible yet

**Comment by rishabhmhjn** [comment]
> Hello @rishabhmhjn same for me, did you find any clue to get it to english? #321 seem to show that it is not possible yet

Not yet! I look forward to any possible solution in the coming time

**Comment by noyhrynban** [comment]
This particular problem seemed to be resolved by running through **sudo** and #321 is probably closer to the real issue.

**Comment by sdl1998** [comment]
Use micro usb cable, don't use type c .I tried all day and finally figured it out.

**Comment by noyhrynban** [comment]
Closing in leu of #321

**Comment by githubuser88442** [comment]
This issue is closed but not without a clear solution. Luckily, I found a solution for this myself:
In the a7s III settings, go to セットアップ (The yellow briefcase icon) > USB > USB接続 > and change it from オート (auto) to マスストレージ (mass storage). Even though the camera automatically showed "マスストレージ" (mass storage) when connected to the PC (Mac with Parallels Ubuntu in this case) via USB connected, unintuitively, out of all the solutions, this one worked!
