### ISSUE TITLE
Error 129 Unlock All Languages A7M4

### ISSUE THREAD

**Issue by noyhrynban** [ma1co/Sony-PMCA-RE#321]
macOS 12.4

1) Put camera into MSC mode
2) `sudo -H ./pmca-gui.py`
3) Click Start Tweaking (service mode)
4) Click to enable all languages

Output:
> Using drivers libusb-MSC, libusb-MTP, libusb-vendor-specific
> Looking for Sony devices
> 
> Querying mass storage device
> Sony DSC is a camera in mass storage mode
> 
> Switching to service mode
> 
> Waiting for camera to switch...
> Found a camera in service mode
> Authenticating
> Traceback (most recent call last):
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/./pmca-gui.py", line 184, in do
>     self.ui.tweakInterface.setEnabled(self.id, arg)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/platform/tweaks.py", line 179, in setEnabled
>     self._tweaks[name][1].setEnabled(enabled)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/platform/tweaks.py", line 54, in setEnabled
>     self._backup.writeProp(self._name, self.onValue() if enabled else self.offValue())
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/platform/backup.py", line 78, in writeProp
>     return self._props[name].write(data)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/platform/backup.py", line 49, in write
>     prop.write(data[:prop.size])
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/platform/backup.py", line 34, in write
>     self.backend.writeBackup(self.id, data)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/platform/backend/senser.py", line 32, in writeBackup
>     self.dev.writeBackup(id, data)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/sony.py", line 1041, in writeBackup
>     self._sendAdjustControlPacket(*self.SONY_ADJUST_BACKUP_WRITE, dump32le(id) + data)
>   File "/Users/ryan/Repositories/Sony-PMCA-RE/pmca/usb/sony.py", line 993, in _sendAdjustControlPacket
>     raise Exception('Senser adjust control error %d' % res)
> Exception: Senser adjust control error 129

**Comment by iconian6** [comment]
Also having this problem on Windows too.

**Comment by AntoineFacq** [comment]
Same error on Windows

**Comment by AntoineFacq** [comment]
@ma1co thanks for all your work on that repo, do you have any idea on how to fix that error ?

**Comment by AntoineFacq** [comment]
@noyhrynban what version of the Sony Firmware are you running? v1.00 or v1.01?
Perhaps Sony made a change since A7 IV release or v1.01 in way packets are addressed? I mean that’s a possibility

**Comment by noyhrynban** [comment]
> @noyhrynban what version of the Sony Firmware are you running? v1.00 or v1.01?
> Perhaps Sony made a change since A7 IV release or v1.01 in way packets are addressed? I mean that’s a possibility

This was a problem with both 1.00 and after updating to 1.01.

**Comment by sdl1998** [comment]
Use micro usb cable, don't use type c .I tried all day and finally figured it out.

**Comment by noyhrynban** [comment]
> Use micro usb cable, don't use type c .I tried all day and finally figured it out.

I get the same results with micro-USB as USB-C

**Comment by noyhrynban** [comment]
Trying the console this time and trying to unlock the protected settings along the way fails:
```
➜  Sony-PMCA-RE git:(master) sudo ./pmca-console.py serviceshell
Using drivers libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to service mode

Waiting for camera to switch...
Found a camera in service mode
Authenticating
Starting service shell...

Welcome to platform shell.
Type `help` for the list of supported commands.
Type `exit` to quit.
>tweak
1: [X] Disable video recording limit
       13h 01m 00s

2: [ ] Unlock all languages
       1 / 35 languages activated

3: [ ] Unlock protected settings
       Protection enabled

Enter number of tweak to toggle (0 to finish): 3
Success

1: [X] Disable video recording limit
       13h 01m 00s

2: [ ] Unlock all languages
       1 / 35 languages activated

3: [ ] Unlock protected settings
       Protection enabled

Enter number of tweak to toggle (0 to finish): 2
Error: Senser adjust control error 129

1: [X] Disable video recording limit
       13h 01m 00s

2: [ ] Unlock all languages
       1 / 35 languages activated

3: [ ] Unlock protected settings
       Protection enabled

Enter number of tweak to toggle (0 to finish): 0
>exit
Done
```

It appears that the first problem may be that "Unlock protected settings" says it succeeds but maybe doesn't actually.

**Comment by rismanto** [comment]
I got the same issue on ILCE-6100.
Any solution about this?

**Comment by Rad0312** [comment]
got the same issue on a7c

**Comment by AntoineFacq** [comment]
Would like to help on this project but have no knowledge on this part :)

**Comment by henryhu1998** [comment]
same problem a7IV windows

**Comment by tadyu228** [comment]
Hi @ma1co any update in this error. As  @noyhrynban commented that the problem maybe cause by unlock protection shown " success " but not actually

Thanks

**Comment by rjmehra** [comment]
Hi all. I just tried the newest version and it worked on my A7C!
Before now I was getting stopped by the #129 error.
V0.18-18 development build seems to work fine!
Please try that and if it works, share the word with those who had similar problems.

@ma1co you are a legend! Please let me know how I can send you some beer money! :)

**Comment by noyhrynban** [comment]
I just pulled latest (d634e6ce4c61dff6ee4450e1452b234dc9563375) and unlocked my A7M4 on a Mac in Terminal using the console UI. I got a message about a backup error, I think because my cards were ejected. The unlock seemed to take anyway. (I ran it once more just to be sure 😁)

@ma1co I can't thank you enough!

**Comment by WynnterPixel** [comment]
hi, does anyone here still have a copy og v0.18-18 ? cas somebody post it here?

**Comment by winevodka** [comment]
Hi @rjmehra 
Can you help me upload the build of V0.18-18?
I don't know how to download or build it from source code.
Thank you very much!

**Comment by rjmehra** [comment]
> 

Hi winevodka,

So to unlock my A7C I didn't build anything from source. I wouldn't know how to do that anyway.
I just downloaded the Windows executables from here. https://github.com/ma1co/Sony-PMCA-RE/releases/tag/v0.18
And followed the instructions here. https://github.com/ma1co/Sony-PMCA-RE

Hopefully that will work. Let us know how it goes!

Best

**Comment by winevodka** [comment]
Thank you rjmehra,
Since the stable release does not work with my Sony A7iii. I found the development build, and it worked.

**Comment by Erur0su** [comment]
Same issues with 6400. No hopes of things getting solved?
