### ISSUE TITLE
rewind "sony ZV-E10 please add language support" >> ASK dazhbog

### ISSUE THREAD

**Issue by MyN678** [ma1co/Sony-PMCA-RE#347]
@ Dazhbog, 
CC Ma1co

Sorry for rewind this issue again.
I saw you finished updating your Sony VZ-E10 in Jun
How abour your Sony ZV-E10 now? is there any issue after updated ?

Thank you

**Comment by dazhbog** [comment]
Didn't have any issue. I just followed the instructions carefully.

Also please close this issue and reply to the original issue #290 if you still have issues.

**Comment by dazhbog** [comment]
I replied to you in #290 

@ma1co or @MyN678 Please close

**Comment by MyN678** [comment]
Thank you Ma1co and Dazhbog

**Comment by NandaA7iii** [comment]
> 

im newbie here,if you dont mind can you teach me how to add english language to my japanese a7iii ?  im so sad cant use my camera, please help me thank you
