### ISSUE TITLE
Paid apps

### ISSUE THREAD

**Issue by Maleewich** [ma1co/Sony-PMCA-RE#35]
Is it possible to download paid applications? And do APK files exist with them? 
Maybe someone can send these APKs? I apologize if such a topic has already been.

**Comment by TheFlashBold** [comment]
If someone has bought the timelapse app i would like it too.
Or if someoe programs it.

**Comment by Bostwickenator** [comment]
Stealing is bad mkay?

**Comment by TheFlashBold** [comment]
Yes it is but 10€ for a timelaps app is worse.
Or you can buy it for me lel.

**Comment by obs1dium** [comment]
Sony's apps may be overpriced, but this is not the place to pirate them.

My BetterManual app includes a simple timelapse feature, maybe it's sufficient for your needs.

**Comment by TheFlashBold** [comment]
Yes you are right, i am just upset about the price.
Does your app work for the rx100iv?
Thanks for the response.

**Comment by obs1dium** [comment]
I'd expect it to work, but don't really know. Just give it a try, the worst thing that can happen with these apps is the camera locking up. Remove the battery if that should happen.

**Comment by TheFlashBold** [comment]
It works, but my camera crashes after the timelapse. And i have to make a video of all the pictures afterwards. I'll try to make a dedicated timelapse app from your source.
Thanks

**Comment by obs1dium** [comment]
Ah, that's too bad. It'd be great to see more homebrew apps, though!

**Comment by TheFlashBold** [comment]
Which ide did you use?

**Comment by obs1dium** [comment]
Android Studio. I wrote a bit about it here: obs1dium/BetterManual/issues/3

**Comment by TheFlashBold** [comment]
Thanks!

**Comment by Deph0** [comment]
I suggest trying the timelapse mobile app that talks to the PlayMemories api, it's pretty a pretty good app. If your camera isn't listed, try out the different models and see if it connects.

https://github.com/ThibaudM/timelapse-sony

**Comment by ma1co** [comment]
Pirating is definitely not a goal of this project. If you want to use the official apps, go and buy them.
