### ISSUE TITLE
Development builds no longer available (support for A7M4)

### ISSUE THREAD

**Issue by AndreG-P** [ma1co/Sony-PMCA-RE#355]
@ma1co On 30th August you made a couple of refactory changes and wrote in issue #292 the following:

> In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for these cameras, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).

Unfortunately, the development builds are no longer available and the latest release is from 8 April. Any updates on publishing a new stable release or a new development build?

**Comment by bigorbi** [comment]
Here is the link for the latest dev build;
https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip

**Comment by Pikacciu** [comment]
Hello @AndreG-P ,

I struggle with my a7IV to unlock languages, if you succeed, could I ask you some advices on how to proceed please?

**Comment by AndreG-P** [comment]
@Pikacciu It's a bit tricky. You first need the newest build (not the newest stable build). That's what this issue was about so use the link bigorbi posted to get that.

After that, you have to follow the readme for your specific OS. I was working with windows here because I got some errors in linux. For windows, you need to install drivers via [Zadig](http://zadig.akeo.ie/) because Windows uses different drivers by default. And you need to install the driver twice (one time for each mode of the camera) but that's explained in the readme (see service mode -> Windows Drivers).

There are only two issues I encountered. First, dont use the GUI (didnt work for me). Second, you must be connected to the PC, in servicemode, with the custom driver installed and THAN use the camera to change the language (while stay connected). Somehow, I unlocked the language settings but it was invisible again when I disconnected the camera from the PC. So you need to go the language menu while connected and in service mode.

The console version was also straight forward. I didn't recall exactly the settings but you just start it as described in the readme and use the updatershell. You can use help or something similar to get all settings. You need tweaks and here you find "unluck languages" or something like that.

**Comment by Pikacciu** [comment]
It worked perfectly!!

I cannot thank you enough, and @ma1co even more!

**Comment by wc3isk** [comment]
@AndreG-P Do u remember how to unlock language menu ? My A7IV language menu didn't show up after servicemode.

**Comment by AndreG-P** [comment]
@wc3isk I wasn't able to locate it at first either but as I said, the key was

> So you need to go the language menu while connected and in service mode.

For some reason the language menu stayed hidden if I'm not activalely connected to the PC and active service mode. So while being connected to the PC, search the language settings.

At least that did it for me and was not clear in the docs.

**Comment by Harrywuzzz** [comment]
When I launch the pmca-console from the above download link it quits automatically after 1 second, any ideas team?

**Comment by Harrywuzzz** [comment]
Have figured it out, unlocked 35 languages but as you said the langugae setting remains hidden on the camera depite me keeping it in service mode and connected. Any ideas? Or do you remember what tab the setting popped up for you @AndreG-P

**Comment by Harrywuzzz** [comment]
Thank you so much for your help team!

After the language tweak, will future firmware updates brick my device?

**Comment by Sujygunsmoke** [comment]
> Thank you so much for your help team!
> 
> After the language tweak, will future firmware updates brick my device?

it work !

**Comment by lijigiri** [comment]
> Here is the link for the latest dev build; https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip

This particular link is not working does anyone have the latest build.
