### ISSUE TITLE
Windows operational procedure occurred errors

### ISSUE THREAD

**Issue by Zang-Rui** [ma1co/Sony-PMCA-RE#36]
Tip:
How to solve it,please?

**Comment by ma1co** [comment]
@Zang-Rui I need some more information. Which executable are you trying to run? Which Windows version? Maybe your executable is corrupt, can you download it again?

**Comment by Zang-Rui** [comment]
“pmca-console-v0.12-win.exe” “pmca-gui-v0.12-win.exe” These two procedures have occurred the same mistakes and I have re-downloaded it also have tried the old version but it didn't work. Windows 10

**Comment by ma1co** [comment]
Do you have non-ascii characters in your windows username? If yes, try the following:

* Create a new directory outside your user profile, e.g. C:\Temp
* Set your _TMP_ environment variable to the path of the directory created above
* Start pmca-gui

**Comment by Zang-Rui** [comment]
The user name is in Chinese.The variable problem about changing the TMP environment still exists.please see Attachment.
![qq 20170707204201](https://user-images.githubusercontent.com/29837201/27961850-b62b3aee-6362-11e7-8986-92c7c8860366.png)
![qq 20170707210311](https://user-images.githubusercontent.com/29837201/27961851-b62fee54-6362-11e7-88fd-7d7506835124.png)

**Comment by Zang-Rui** [comment]
Has been resolved, thank you.
