### ISSUE TITLE
Upload to camera via script doesn't work

### ISSUE THREAD

**Issue by MrLaffer** [ma1co/Sony-PMCA-RE#4]
Hello,

the upload to camera via script doesn't work.
I get the following error:

sudo python pmca.py install -d libusb -f PMCADemo-release-0.7.apk 
Using libusb
Looking for Sony MTP devices
Traceback (most recent call last):
  File "pmca.py", line 103, in <module>
    main()
  File "pmca.py", line 99, in main
    installCommand(args.url, args.driver, args.apkFile, args.outFile)
  File "pmca.py", line 68, in installCommand
    devices = [dev for dev in driver.listDevices() if dev.type == USB_CLASS_PTP and dev.idVendor == SONY_ID_VENDOR]
  File "/home/jens/Projekte/pmca/Sony-PMCA-RE-master/pmca/usb/driver/libusb.py", line 11, in listDevices
    interface = dev.get_active_configuration().interfaces()[0]
AttributeError: 'Configuration' object has no attribute 'interfaces'

**Comment by ma1co** [comment]
How did you install pyusb? Which version?

**Comment by MrLaffer** [comment]
Via package manager (Yast - OpenSuSE).
Version: 1.0.0.-26.1

**Comment by ma1co** [comment]
Oops, that's pyusb 1.0.0b1, i developed and tested against version 1.0.0b2. For now, you can either install the newer version with pip or try to replace the line `dev.get_active_configuration().interfaces()[0]` by `dev.get_active_configuration()[0]`

**Comment by MrLaffer** [comment]
Hello,
I have upgraded my pyusb. Now it works (but only with python 2.7). Thank you.
