### ISSUE TITLE
Sony Alpha7 (ILCE-7) not supported?

### ISSUE THREAD

**Issue by robakra** [ma1co/Sony-PMCA-RE#40]
The OpenMemories Tweak does not work fully on my Sony Alpha 7 (ILCE-7)
Installation is no problem. The app also runs fine and extended language and video settings can be applied.
The language setting (35 languages) works fine but the video recording still ends after 29 minutes.
I tried all kinds of video settings and applied the twaek on both firware version 3.10 and the latest 3.20 with no luck.
Any clues?

**Comment by filu55** [comment]
The OpenMemories Tweak does not work fully on my Sony Alpha 7R II. Installation ist no Problem.
LOG: Loading plugin / Starting task / Got task key / Cancellation plugin / Plugin cancelled / Starting download to camera / Error: Network Connection.
Whats wrogn? Camera on usb Connection ist set on MTP
thanks, filu55

**Comment by ma1co** [comment]
@filu55 Please try [pmca-gui](https://github.com/ma1co/Sony-PMCA-RE/releases).
