### ISSUE TITLE
Possible to set Serial No. / Product ID via Sony-PCMA-RE? (Sony FDR-AX30 mainboard "VC-1038" to FDR-AXP33)?

### ISSUE THREAD

**Issue by Muxfeldt** [ma1co/Sony-PMCA-RE#414]
Hi,
i have a defect Sony FDR-AXP33 mainboard (broken connector holders).
The mainboard is responding via USB normally.

Now i bought a new VC-1038 mainboard. It ist assembled in the camera and in principle the camcorder is working.

But the VC-1038 has the AX30 firmware 1.10. 
So the projector, the EVF and the internal memory is not working. (i hope this is only because of wrong information on the new mainboard)

It is not possible to flash AX33.

In the service manual several steps are describe: In case of replacing the board you have to use "Adjust Station"? and save the old settings (USB Serial No. + Product ID) of the defect mainboard and transfer them to the new one.

I had read out Model + Product Code + Serial Number. 

But i am not finding the Sony Software (Adjust Station) - so how to write to new mainboard?

So the question is: Is it possible to set Serial No. / Product ID via Sony-PCMA-RE? Or can i transfer e.g. a complete setting from old mainboard to the new one. Or does anyone have another idea?

Thank you in advice!

**Comment by Muxfeldt** [comment]
I have some news after copying Backup.bin 

1) The EVR is now working fine :-)
2) The display is now bluish. It looks like the red channel is missing. This is for menu and captured images. In EVR everything is fine. So the sensor is ok and only the display has a problem (or a display setting). The display was ok before i copied the Backup.bin, so there is no physical error.
3) The projector button itself is now working. The projector lamp is switching on - but than a test-image? with black/white blocks is displayed
4) in Menu/Installation/Version is now AXP33 + V 1.10 displayed - this seems ok
5) Via pmca the serial number + product id is the correct one - from old motherboard. - ok

After this result i copied - hope that can fix projector and display:

- Backup.bin
- Backup.bak
- DmmConfig.bin
- init_bk.bak
- kemco.txt
- ulogio.bin

Everything as before (bluish display).

And the correct firmware Tool from Sony Website is not working. 
It should be "Update_FDRAX33NMV110" - but there is no firmware found.

If i start "Update_FDRAXP35V110" - which is for FDR-AX30 - a firmware is found >= 1.10 (no update possible because already installed)


Have anyone an idea what i can do to bring my display back to normal colors and the projector to switch on the correct image instead displaying black/white blocks?

Thank you

**Comment by Muxfeldt** [comment]
Now i unpacked the correct firmware for AXP33, modified config.yaml (increased version) and packed it.
This firmware i can upload to the camcorder and the new version is correctly displayed.
But the display has always wrong colours (looks like BGR instead RGB - Green channel is correct, the others are switched)

So i restored Backup.bin and uploaded correct firmware - EVR is working, but display and projector not correctly.

In service manual is written, that serial number of projector unit has to be restored. And in "Adjust station" as "Projector Data Reference" should be executed.

Did anyone hear about these things or knows how to set correct projector unit?

**Comment by Muxfeldt** [comment]
I found out how to change product code and serial number.
Reverse flashing to V 1.00 firmware was successful, too.
Projector ist not working - but this seems to be another problem.
Closed.

**Comment by ckrzyzak** [comment]
Where did you find the backup file? I am trying to do the same thing for a hx30v which has hx20v software on the mainboard.

**Comment by Muxfeldt** [comment]
Hi. I had several boards and created a backup from the settings (backup.bak). So i had both versions of the backup.bin. But you can search in the unpacked firmware upgrade files. You have to unpack the .dat file. In my case the files are in firmware.tar_unpacked\0110_backup. Here are several files with the camera name.bak. You can use one of them and rename it to backup.bak. But be careful! I have done this one time with the wrong file - this board is bricked now.

**Comment by ckrzyzak** [comment]
So I have the old board that has all of the files for the hx30v which works but the lcd connector is broken. I want to take all of the files off of that one and put them onto the board which was from a hx20v. There is no firmware update available for the hx30v from Sony to unpack and redo the files. I am very new to reprograming Sony cameras so I don't know what the proper commands are either.

**Comment by ckrzyzak** [comment]
Do you have a discord or something we can chat on because I feel like I'm either super close or super far from making this work? @Muxfeldt

**Comment by ckrzyzak** [comment]
Hello, I know it has been a couple months but would you still be able to help me with this issue?

**Comment by Muxfeldt** [comment]
Hi, 
if you google for "pcma-re", you will find some projects - on this way i learned the necessary parts. But the very first source to look for the correct commands is here:
[https://github.com/ma1co/Sony-PMCA-RE](https://github.com/ma1co/Sony-PMCA-RE)

I have a full list of commands in my personal documentation, but i don't want to post it here, because if you (or another one) uses it on the wrong way, your board can be bricked. So it is very important that you read and understand, what you are doing there. "the route is the goal"

But perhaps this can help:

**To connect to camera:**
pmca-console-v0.18-win.exe updatershell -m FDR-AXP33

shell rm /setting/updater/mode
shell reboot

**This is for creating a backup:**

Run pmca-console updatershell
Run the following updatershell command to dump the firmware (this will take some time to complete): pull /dev/nflasha
Run the following updatershell command to dump the bootloader partitions: bootloader
Run the following updatershell command to reboot your camera back to normal mode: exit
You should now have files called nflasha and boot1 to boot5 on your computer.

With fwtool-v1.2-win.exe you can unpack and repack the firmware. But if i understand you correct, you will not need to repack. You only need to create a backup (**pull**) from your broken cam and **push** the backup.bin to target cam.

This can look like this:

push Boards\AXP33\Firmware-Dump\unpack_nflasha\nflasha2_unpacked\Backup.bin /setting/Backup.bak

But you can pull single files, too. So only pull backup.bin from broken cam and send it to target cam.

THIS IS AT YOUR OWN RISK.

BUT:
Why don't you repair the hardware? You can put the correct display to the broken cam (which has the correct firmware). Or you can change the board instead modifying the firmware?

I hope, that the commands can help. But read carefully every command documentation so you are understanding what it is doing.
And again: I think that you can fix the problem by repairing the hardware.

I hope that you are successful in your project

Regards, 

Andreas

**Comment by ckrzyzak** [comment]
Hello,

I have pulled the firmware (nflasha) and the bootloader (boot1) so if i understand you correctly i need to use fwtool-v1.2-win.exe to pack them up into a backup. When going to pack them I am prompted with this

usage: fwtool-v1.2-win.exe pack [-h] (-c CONFIGFILE | -d DEVICE)
                                [-u UPDATERFILE | -b UPDATERBODYFILE]
                                [-f FIRMWAREFILE] -o OUTDIR

Besides -f which is nflasha and -d which for my case would be hx30v I believe where do i implement the bootloader file as well as the other files to fill in?

I am the board currently has hx20 software on it which i want to upgrade to hx30v software.

The parts to swap it out are too expensive new and when getting used ones they come broken.

After packing the file where do i push it to on the camera?

Thank you for all of your help,
Christopher
