### ISSUE TITLE
USB Error

### ISSUE THREAD

**Issue by Gabitox** [ma1co/Sony-PMCA-RE#42]
I made a custom  APK modifying the  obs1dium  FocusBracket app. The problem is that when I try to install it on a Sony a6000 I get this error (via the windows app):

Querying MTP device
Sony Corporation ILCE-6000 is a camera in app install mode

Using local server
Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading 100%
Installing 0%
Traceback (most recent call last):
  File "<string>", line 76, in do
  File "pmca\commands\usb.py", line 224, in installCommand
  File "pmca\commands\usb.py", line 72, in installApp
Exception: Communication error 100: Error completed

And via the browser plugin:

Loading plugin

Plugin loaded

Starting task

Got task key

Cancelling plugin

Plugin cancelled

Starting download to camera

Progress: Uploading 0%

Progress: Uploading 100%

Progress: Downloading 100%

Progress: Installing 0%

Device error: General

Starting task

Got task key

Cancelling plugin

Plugin cancelled

Starting download to camera

Progress: Uploading 0%

Progress: Uploading 100%

Progress: Downloading 100%

Progress: Installing 0%

Device error: General

What am I missing? Why this worked with the original FocusBracket apk and  it then fails to install a costum made app?

**Comment by ma1co** [comment]
You cannot reinstall / update an Android app if the signature has changed. Uninstall FocusBracket or change the application id of your app to resolve the issue.

**Comment by Gabitox** [comment]
I did it and now it works. Thanks.

**Comment by Gabitox** [comment]
Btw great job.The Framework is awsome.
