### ISSUE TITLE
issue installing tweak on RX100M3

### ISSUE THREAD

**Issue by drumstick77** [ma1co/Sony-PMCA-RE#421]
Hi, I'm not able to get this applied/installed. I used the GUI and used Zadic to replace the driver too, but it is to no avail. not sure what I've done wrong. please help. thanks

**Comment by danni551** [comment]
do you have the driver for service mode?

**Comment by drumstick77** [comment]
Yes, I believe so, I did this --> In Zadig, check Options -> List All Devices, select the camera, select libusb-win32 and click Replace Driver.

**Comment by drumstick77** [comment]
hiya, your program works perfectly. It was me that didn't understand the instruction or perhaps the instructions can be updated with a bit more detail direction for people like me. I thought I had to go to tweak tab, but looking into the GUI in more detail, found that it is actually under installation. Thanks again
