### ISSUE TITLE
I want to remove unwanted language from Sony A7 camera

### ISSUE THREAD

**Issue by fortheworld2017** [ma1co/Sony-PMCA-RE#425]
Hi

I unlocked all languages. but I want to remove unwanted language from my camera.

Any advice?

Thank you so much

**Comment by fortheworld2017** [comment]
I found the way. Thank you so much

:)

**Comment by Lyashenko-Alex** [comment]
Hi

**Comment by Lyashenko-Alex** [comment]
@fortheworld2017 How did you remove unwanted language? Will you please list steps?

**Comment by fortheworld2017** [comment]
Sure. I'll write the steps

**Comment by fortheworld2017** [comment]
> 

Which language do you want remove?

**Comment by Lyashenko-Alex** [comment]
@fortheworld2017 Thanks for your advise. I'd like to remove all languages except for Russian, English and Chinese.

**Comment by Lyashenko-Alex** [comment]
Is it impossible?

**Comment by fortheworld2017** [comment]
It's possible 
https://drive.google.com/file/d/1Oo3m4kpeMEDFIIV_QSxtb1yiNEy_x9zp/view?usp=sharing
What is your model?

**Comment by Lyashenko-Alex** [comment]
Awesome!!!
My camera model is ILCE-6000 (Alpha 6000).

**Comment by Lyashenko-Alex** [comment]
@fortheworld2017 Please teach me how to do it.

**Comment by fortheworld2017** [comment]
@Lyashenko-Alex please give me your email

**Comment by Lyashenko-Alex** [comment]
@fortheworld2017 test880312@gmail.com

**Comment by Lyashenko-Alex** [comment]
@fortheworld2017 Will you please share instruction step by step?

**Comment by fortheworld2017** [comment]
I sent new build exe file as zip to your email

**Comment by Lyashenko-Alex** [comment]
@fortheworld2017 There is no an exe file. Will you please resend?

**Comment by Lyashenko-Alex** [comment]
@fortheworld2017 ?

**Comment by Lyashenko-Alex** [comment]
@fortheworld2017 Will you please advise? Or should I try another solution?

**Comment by Lyashenko-Alex** [comment]
@fortheworld2017 I am not a technical. Please teach me step by step. Thanks.

**Comment by Vhappy86** [comment]
> I found the way. Thank you so much
> 
> :)


Hi,
Sorry to post message  in between.
I bought camera from japan ZV E10-ii. I successfully changed language to English.
I need only english language and I selected, but when I scroll in language menu camera got restart.
I dont have any issue as I can use english language.
I'm worried about if I do factory reset or firmware update camera will still works fine or it will keep on restarting (As this issue reported from some users)
If it can cause error can you help me out how to delete those language which are causing restart error.

Thanks in advance for your effort
