### ISSUE TITLE
Nex-7 tested

### ISSUE THREAD

**Issue by RigoRos** [ma1co/Sony-PMCA-RE#45]
I don't know, if this camera has the android feature, too.

Maybe it is possible to install apps on this, not official supported camera, too. 
The given error code was: 
Mass storage error: Sense 0x5 0x20 0x0.

**Comment by Bostwickenator** [comment]
The NEX-7 doesn't have Android :(.

**Comment by RigoRos** [comment]
Sad... :cry: but thank you for quick response. 
Are there tries to port it?

**Comment by Bostwickenator** [comment]
That's not really something that is feasible. Probably tens of thousands of work hours.

**Comment by ma1co** [comment]
@RigoRos 
There is a new experimental way to tweak settings on older cameras using the firmware update functionality. Read more about it [here](https://github.com/ma1co/Sony-PMCA-RE#tweaking-camera-settings). Keep in mind that you are probably the first person to test this on a NEX-7, so your mileage may vary. If you attempt anything, please let us know!
