### ISSUE TITLE
Sony RX10 IV Problem with pmca

### ISSUE THREAD

**Issue by camperschwein** [ma1co/Sony-PMCA-RE#46]
If i will install the Open Memories Tweak the folloing messenge is comming:

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX10M4 is a camera in MTP mode

Model:              DSC-RX10M4
Product code:       0080817550
Serial number:      -
Firmware version:   1.00

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX10M4 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "<string>", line 73, in do
  File "pmca\commands\usb.py", line 211, in installCommand
  File "pmca\commands\usb.py", line 31, in switchToAppInstaller
  File "pmca\usb\sony.py", line 180, in switchToAppInstaller
  File "pmca\usb\sony.py", line 147, in _sendCommand
  File "pmca\usb\sony.py", line 94, in sendSonyExtCommand
  File "pmca\usb\__init__.py", line 58, in _checkResponse
Exception: Response code not OK: 0x2006

Can someone help me ?

**Comment by ma1co** [comment]
The RX10M4 does not support the official camera apps. We don't know if there is an android subsystem or not. I also suppose that it uses the same new firmware encryption method as the A9 (which we cannot decrypt). So for now, there is nothing we can do, the RX10M4 is not supported.

**Comment by vienmnguyen** [comment]
Is there any idea if there is any hope that one day it may be possible to decrypt the firmware for the A9/RX10M4? I've read some forums suggesting Sony may release a firmware update in the future that will add support for the official camera apps, but it's just a rumor at this point.
