### ISSUE TITLE
A6300 stuck in service mode.

### ISSUE THREAD

**Issue by ZuwaiiVR** [ma1co/Sony-PMCA-RE#462]
After accessing Service shell through the console i was able to list  and view things on the shell. But after I turned off the camera and back on, the display stayed Black, the PC recognize the camera as "Sony USB Device" that we installed with Zadig (Libwin32). 

Now the console program doesn't have a working shell, it still says, Authenticated, but as soon you enter shell, it will reply Error:.
rebooting or taking the battery out dont work, even without battery the camera still connects to PC in service mode.

Any know how to change modes within Service mode? or atleast getting out of it, since it litterly is a brick right now.

I Tried:
in Gui, Info button dont work. firmware updating don't work either, wrong mode.
Also, the red SD card led is on. (no blinking)
Its current USB VID 054C PID 0336 just in case.

please let me know.
Thanks, Zuwaii.

**Comment by ZuwaiiVR** [comment]
Ok this can be closed~ it seems when I look back I ran a command "up.sh" just out of curosity, its output was, "next boot...   Updater mode".. so meanwhile it actually created a file in "/setting/updater/mode1" so upon next boot it sees that file and litterly goes into, well it should be updater mode, but it was Service Mode with PID 0336 usb reporting.

I unpacked the firmware and looking what up.sh was doing, and realize, if I was able to remove the mode file, the camera would work again, appearantly Shell isnt working, but I could still read and write to the backup file. after learning how up.sh worked I created another file "mode6" and pushed into the camera. after that i unplug the USB and battery, and... it's alive again.

mode6 file had a description of 
" ### change to version skip mode
func_verskip()
{" in up.sh

the files are just 0 bytes.

so it's was maybe worth trying it, and..... it booted normally..
Thank god.

Made a mistake not reading the sh script first, and glad I was able to fix it.  if there was a rm command to remove files from the camera, it would be nice to have it in there aswell!

so if anyone ran into the same problem this might help~ 

Thanks
ZuwaiiVR~

**Comment by juniorrantila** [comment]
Thank goodness for this. Bricked my A7 a few years back (probably) the exact same way. Ran all the executable files I could find and when turning off and on again the red light came on and screen didn't turn on. Creating the empty "mode6" file and pushing it to "setting/updater/mode6" seems to have made it work again. :)

**Comment by Andrey-Andriyuk** [comment]
@ZuwaiiVR @juniorrantila Hi guys. I bricked my camera in the same way — I ran up.sh, and as a result, on the next boot, the camera got stuck in service mode. Could you tell me how you managed to replace the mode6 file? When I try to access serviceshell, I see the following:
```
Found a camera in service mode
Authenticating
Starting service shell...
```
and then it times out with an error.
Do I understand correctly that in your case, instead of an error, there were options to upload or download files to the camera?

I tried increasing the timeout to 10 minutes, but it didn’t change anything — the same error appeared after 10 minutes of waiting:
```
Authenticating
Starting service shell...

/
Traceback (most recent call last):
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca/usb/driver/generic/libusb.py", line 79, in read
    return self.dev.read(ep, length, timeout).tobytes()
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrei/repo/Sony-PMCA-RE/venv/lib/python3.13/site-packages/usb/core.py", line 1043, in read
    ret = fn(
            self._ctx.handle,
    ...<2 lines>...
            buff,
            self.__get_timeout(timeout))
  File "/Users/andrei/repo/Sony-PMCA-RE/venv/lib/python3.13/site-packages/usb/backend/libusb1.py", line 850, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                       dev_handle,
                       ^^^^^^^^^^^
    ...<2 lines>...
                       buff,
                       ^^^^^
                       timeout)
                       ^^^^^^^^
  File "/Users/andrei/repo/Sony-PMCA-RE/venv/lib/python3.13/site-packages/usb/backend/libusb1.py", line 958, in __read
    _check(retval)
    ~~~~~~^^^^^^^^
  File "/Users/andrei/repo/Sony-PMCA-RE/venv/lib/python3.13/site-packages/usb/backend/libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca-console.py", line 104, in <module>
    main()
    ~~~~^^
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca-console.py", line 88, in main
    senserShellCommand()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca/commands/usb.py", line 705, in senserShellCommand
    CameraShell(SenserPlatformBackend(SonySenserCamera(device))).run()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca/platform/__init__.py", line 51, in run
    self.backend.start()
    ~~~~~~~~~~~~~~~~~~^^
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca/platform/backend/senser.py", line 10, in start
    self.dev.readHasp()
    ~~~~~~~~~~~~~~~~~^^
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca/usb/sony.py", line 1014, in readHasp
    return self._sendProductInfoPacket(*self.SONY_PRODUCT_INFO_READ_HASP, dump8(0))
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca/usb/sony.py", line 985, in _sendProductInfoPacket
    res, data = self.dev.sendSenserPacket(self.SONY_PFUNC_ProductInfo, header + data)
                ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca/usb/sony.py", line 857, in sendSenserPacket
    d = self.driver.read(self.SenserPacketHeader.size + l)
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca/usb/driver/generic/__init__.py", line 94, in read
    return self.backend.read(self.epIn[ep], length, timeout)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrei/repo/Sony-PMCA-RE/pmca/usb/driver/generic/libusb.py", line 81, in read
    raise GenericUsbException()
pmca.usb.driver.generic.GenericUsbException
```

**Comment by ZuwaiiVR** [comment]
@Andrey-Andriyuk  as i remembered before there are some commands to push a file to the camera without entering shell.
It's been long time ago for me, and since after that I never touched these stuff anymore. removing the 30min limit on the camera was enough, as I dont know what to do in android side of the camera I just left it as is.
