### ISSUE TITLE
Sony DSC RX100: NTSC / PAL 

### ISSUE THREAD

**Issue by tAz-07** [ma1co/Sony-PMCA-RE#463]
Hi,
I have a Sony DSC RX100 and cannot apply tweaks on the device. 

I cannot install app (system not compatible)

But then I have not the NTSC/PAL option in the menu

It is a limitation of the RX100 (M1 I guess) ?

Thanks !

**Comment by tAz-07** [comment]
I have tried on another PC , no error this time but no option to switch PAL/NTSC then

**Comment by dreambold** [comment]
Did you try on a Ubuntu machine?

**Comment by tAz-07** [comment]
no , I have tried also in MPT with Zadig on a secondary PC : I have no error and when I come back to tweak I can see all boxes are checked . But still no new option or if I count the number of language (suppose to 35/35) I have only 25.

**Comment by tAz-07** [comment]
my firmware is 1.10

**Comment by dreambold** [comment]
You can try on an Ubuntu VM, just let me know if you need help with it

**Comment by tAz-07** [comment]
yes I would appreciate some help I have tried on a xubuntu last version but can't install dependencies. Is there a procedure somewhere ?

according to that page https://openmemories.readthedocs.io/devices.html my device should be supported

**Comment by dreambold** [comment]
Do you have Teamviewer?

**Comment by tAz-07** [comment]
no :/

**Comment by dreambold** [comment]
Please install it and let me know. asenfan0723@gmail.com is my email

**Comment by tAz-07** [comment]
installed , I contact you

**Comment by tAz-07** [comment]
thank again for your help Dreambold.

So using my linux box I see 2 options : Unlimited video unlock and NTSC/PAL one. 

After a quick test I confirm my video can be > 30min  : great !

Regarding my PAL rx100 I want to change to NTSC to have 1080P60P mode instead of 1080P50P I have not the option in the menu.
I guess it is part of the other project to install an app  ? app are not compatible with my first gen RX100. And I have not seen an option from the tools to force NTSC by default.

**Comment by tAz-07** [comment]
hum maybe it is a limitation of the m1 , I will close that ticket.
