### ISSUE TITLE
ILCE-6000 switching to app install mode failed, and auto disconnect USB...

### ISSUE THREAD

**Issue by Mmzer** [ma1co/Sony-PMCA-RE#47]
```bash
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to app install mode
Waiting for camera to switch...
Looking for Sony devices
Looking for Sony devices
Looking for Sony devices
Looking for Sony devices
Looking for Sony devices
Looking for Sony devices
Looking for Sony devices
Looking for Sony devices
Looking for Sony devices
Looking for Sony devices
Operation timed out. Please run this command again when your camera has connected.
```

**Comment by ma1co** [comment]
What does the camera do? Does the [browser plugin](https://sony-pmca.appspot.com/) work?

**Comment by Mmzer** [comment]
@ma1co 
The camera didn't do what. Have even on usb, and using the mass storage mode.
The [browser plugin](browser plugin) didn't work.I use the `pmca-console-v0.11-win.exe`and`pmca-gui-v0.11-win.exe` to install the app.

**Comment by ma1co** [comment]
@Mmzer What about the official app store (playmemoriescameraapps.com)? If this doesn't work for you, I can't really help...

**Comment by Mmzer** [comment]
@ma1co
I haven't tried before.....Thank for your help
