### ISSUE TITLE
[a6000] Restarts after shutter release, while using a dummy battery connected to powerbank 

### ISSUE THREAD

**Issue by miffleswaffles** [ma1co/Sony-PMCA-RE#48]
everything works fine, after the tweak, i got this issue only on when i took pictures it would restart, but on dummy battery on video mode it works fine,

is there an fix or at least revert it back to original settings?

my firmware was 3.20

thanks and hope this well get resolved...

more power

**Comment by Bostwickenator** [comment]
I think you are in the wrong project. Can you go to https://github.com/ma1co/OpenMemories-Tweak open this issue and detail which settings you changed with the Tweak. Then close this issue. Thanks

**Comment by miffleswaffles** [comment]
oh sorry,
