### ISSUE TITLE
Wifi File Transfer App

### ISSUE THREAD

**Issue by tuannx94** [ma1co/Sony-PMCA-RE#49]
Can anyone create an app which can transfer file through wifi on sony alpla. 
It make camera become a ftp server, and we can use PC or smartphone to download files from it (like RAW,etc..)
Thank you!

**Comment by tuannx94** [comment]
thank you, but this is not what i was talking about.
i mean the app can create ftp like this [app](https://play.google.com/store/apps/details?id=com.mbapp.ftpserver). 
i have searched and tested all app on playstore, and found one app (and some clone of this app) can run on sony alpha camera and worked. but it make camera unstable, cant control anything, cant shutdown and i have to remove battery. Then when i turn on camera again, it take long time to start.

**Comment by mungewell** [comment]
Maybe I'm missing the point, but doesn't the official 'Smart Remote' (Camera APK) allow tranfers of files from the camera, using the 'Remote Camera API'? Does this not work for you?

Acknowledge that this also requires either the 'PlayMemories' (Phone APK) or alternative implementation/app on the PC.

**Comment by tuannx94** [comment]
Smart remote can only transfers file that you shoot, not other files in your SD card. I want to transfer files with high resolution like raw file, or maybe just high resolution jpeg. but playmemories can only transfers 2M jpeg, although i choose "original".

**Comment by zen67** [comment]
You can install Files Zilla FTP. Setup FTP server. Turn ON WiFi /via OpenMemories-Tweak/. Start FTP server - DONE!
You have FTP access to / (root) on A7 & etc.
