### ISSUE TITLE
Skip the ARW files?

### ISSUE THREAD

**Issue by windyweather** [ma1co/Sony-PMCA-RE#50]
WOOPS.  Sorry this is for STG Uploader, not your PMCA utility. I'll go find a better place for this comment.

Kudos. Even works on my old out of date NEX-6 camera.
I had a little trouble figuring out how to put in the WPA password, but that's not your problem. When I tried to connect to the other WiFi that I have I could put in the pw without issue.

For STG Uploader. I'll post this to Alex Gee if I can figure out how.
But I take photos with JPG + ARW and can't see a way to skip uploading the ARW to google. Takes too long doing both, obviously. Just a checkbox to skip those would be nice.
Thanks again.
ww

**Comment by ma1co** [comment]
Please report this in the [correct repository](https://github.com/Bostwickenator/STGUploader).

**Comment by windyweather** [comment]
Thanks for pointer
