### ISSUE TITLE
Sony Nex F3 clean hdmi output

### ISSUE THREAD

**Issue by firminunderscore** [ma1co/Sony-PMCA-RE#522]
Hello, 
I currently have a sony nex f3 and would like to have a clear HDMI output. Do you know how I can do this? The solutions for the Sony Nex 5N and 6 do not work with this camera.

**Comment by firminunderscore** [comment]
This solution seems to works. 

https://www.youtube.com/watch?v=sUqMf6FcSF8

Thank you Leonardo !

**Comment by kirill3333** [comment]
@firminunderscore Hey man, have you used the same values and params from the video on your camera or it is different? If yes can you share the values you use?

**Comment by firminunderscore** [comment]
No, i'use exactly the same values and its working perfectly

**Comment by KNGLIONHRT** [comment]
How do I do this work around. Im new to this type of thing but I think I can do it with a little guidance. Any help is appreciated.
