### ISSUE TITLE
Support for Sony hx99

### ISSUE THREAD

**Issue by amoweb** [ma1co/Sony-PMCA-RE#523]
Hello,

I tried with my Sony HX99 and this does not recognize this. I think it must be close to the HX90 which is supported.

I'm developer, how can I help?

```
Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX99 is a camera in MTP mode

Getting device info
Using firmware for model DSC-HX99

Unknown device: DSC-HX99
```

**Comment by amoweb** [comment]
I solved the problem.

- I followed the method to install pmca-console on Windows (https://github.com/ma1co/Sony-PMCA-RE#windows-drivers). This is not totally clear but the driver has to be installed twice (this is the meaning of the "Once the camera has switched, repeat the above step to install a driver for service mode" sentance).
- Then run pmca-console serviceshell
- Then type `shell`
- We want to change some values in the /backup/Backup.bin file using the bk.elf command. First verify the initial values of video limit. Type the following 3 commands (for hour, minute and seconds) in the shell:
```
bk.elf read 0x003c0373
bk.elf read 0x003c0374
bk.elf read 0x003c0375
```
You should see respectively 0, 1D and 50 which means 29m50s.

- We change to 13h01m00s which is 13, 1 and 0 with the following commands:

```
bk.elf write 0x003c0373 13
bk.elf write 0x003c0374 1
bk.elf write 0x003c0375 0
```

- Save with this command: `bk.elf s`
- Turn off the camera.
  
I haven't changed the limits in 4K since my camera heats too much.

**Comment by dmitriyteteruk** [comment]
@amoweb 
> I haven't changed the limits in 4K since my camera heats too much.
could you please help to find commands for 4K limits?

**Comment by amoweb** [comment]
Yes, for 4K, have a look at this:

Check that the original values are 0x2c and 0x01 (corresponding to 5 minute) with the following commands

```
bk.elf read 0x003c04b6
bk.elf read 0x003c04b7
```

Change the duration with this:

```
bk.elf write 0x003c04b6 255
bk.elf write 0x003c04b7 127
```

**Comment by Crazp** [comment]
> Yes, for 4K, have a look at this:
> 
> Check that the original values are 0x2c and 0x01 (corresponding to 5 minute) with the following commands
> 
> ```
> bk.elf read 0x003c04b6
> bk.elf read 0x003c04b7
> ```
> 
> Change the duration with this:
> 
> ```
> bk.elf write 0x003c04b6 255
> bk.elf write 0x003c04b7 127
> ```

@amoweb Hello.My camera is wx800,which is a no evf and no raw version as hx99.
I found the commands shows
```
bk.elf read 0x003c04b6  --> 0C
bk.elf read 0x003c04b7  --> 00
```
Just like [RX100 M5](https://github.com/ma1co/OpenMemories-Tweak/issues/130#issuecomment-281532601)

Above address seems just work with RX100M4. It would not crack the limit of 4K recording time.
