### ISSUE TITLE
Sony A7III (ILCE-7M3) no tweaks avaliable in service mode

### ISSUE THREAD

**Issue by asphaltica** [ma1co/Sony-PMCA-RE#526]
Hi everybody!
Latest PMCA 0.18 does not show me service mode button. And as 0.18-22 it does not give me a chance to operate with MTP in updater mode:  ILCE-7M3 does not support custom firmware updates.
But 0.18-22 supports service mode, but when I push "Start Tweaking", process ends with "no tweaks avaliable"
Sony A7III, firmware 4.01

**Comment by asphaltica** [comment]
There were driver problems. Reinstalled driver with zadig 7 everything went fine since.

**Comment by pinchies** [comment]
For those who have an **A7III / ILCE-7M3 / A7M3** and struggled to **unlock the video recording limit** on firmware 4.01:

1. Download the older Zadig 2.7. This is essential, as it installs the libusb-win32 driver with version 1.2.6.0
2. Use the pmca-gui v18-22-ga82f5ba.exe file, NOT the v18 in the releases on this repo, as the one on this repo will not offer you the service mode tweaking, which is required for the A7III.
3. Once the camera is put into service mode, you will see a device in Zadig called "Sony USB device". If not already done, you also need install the libusb-win32 v1.2.6.0 driver here too.
4. If at any point you have used another version of zadig, it is likely you have a newer version of libusb installed like 1.4.0.0, which is incompatible. You need to connect the camera, and uninstall and delete the newer driver, then reboot. Connect the camera again and check that the newer driver has been removed. Then reinstall the 1.2.6.0 driver.
5. If at any point you need to force the camera to enter (and STAY) in service mode, so you can uninstall/install drivers for the Sony USB device, you can use the command prompt version of PMCA with command "pmca-console.exe serviceshell" to enter service mode.

**Comment by d86592** [comment]
can confirm @pinchies method is working, just use [evianita08's mirror](https://github.com/evianita08/pmca_v18.22) in order to succeed. (couldn't find the file so I used this one and confirmed it does indeed work.)

**Comment by aexko** [comment]
I confirm @pinchies method is also working! I'm using an A7C (ILCE-7C). Using zadig 2.7 fixed my issue, thank you so much!

**Comment by d86592** [comment]
> I confirm @pinchies method is also working! I'm using an A7C (ILCE-7C). Using zadig 2.7 fixed my issue, thank you so much!

good for you, glad it worked!

**Comment by d86592** [comment]
anyone know if this can work on 4.02? I was planning on updating but unsure if that will break any features

**Comment by ge0kas** [comment]
anyone know how to LOCK again the device as it was ?
`2: [ ] Unlock all languages
       12 / 35 languages activated

Enter number of tweak to toggle (0 to apply): 0
Error: Cannot overwrite backup`

**Comment by ilirijus89** [comment]
Hello, anybody tried to unlock video limit on A7 iii, on newest fm, or at least on 4.0.2?

Thanks in advance.

**Comment by ilirijus89** [comment]
> anyone know if this can work on 4.02? I was planning on updating but unsure if that will break any features

Did you tried on 4.0.2?

**Comment by okryuk** [comment]
> > anyone know if this can work on 4.02? I was planning on updating but unsure if that will break any features
> 
> Did you tried on 4.0.2?

I did that Yesterday on the most recent firmware and everything works fine. For questions and step-by-step instructions re-read @pinchies comment. If you need exe files in the correct versions, feel free to check my fork of the repo. I used the same files I uploaded into the cmd directory.

**Comment by pseudobacon** [comment]
Also can confirm @pinchies method is working for my a A7C (ILCE-7C)

**Comment by omearamd** [comment]
This is the way!  Worked for ILCE-7M3 4.03

Thanks so much!  I had tried everything else I could think of, but I didn't think of older ZADIG/USB drivers with the newest pcmca-gui v0.18-22
