### ISSUE TITLE
A7C2 Issues

### ISSUE THREAD

**Issue by kimchiandgogi** [ma1co/Sony-PMCA-RE#534]
Just bought a A7C2 from Japan but am having issues unlocking the language. I followed the instructions but the PMCA-GUI version available for download does not have the option of Service tweaks. I found the newest version .18-22 and it states that no tweaks are available. I then found another version .18-14 and it gives me the option to unlock all languages so that is the version I will be going with. However, when I attempt to unlock the languages the camera keeps on coming out of Mass storage mode. 

Is it an USB connection issue or do you think it is an issue with the version I am using?

**Comment by apk01k** [comment]
https://github.com/ma1co/Sony-PMCA-RE/issues/459#issuecomment-2208164901

You probably have firmware 1.02 like me.
Linux worked for me. try with the live linux iso from this comment.

Windows seems to have issues with the usb drivers.

**Comment by apk01k** [comment]
https://github.com/ma1co/Sony-PMCA-RE/issues/527#issuecomment-2211825668

This user solved on a a7r4 with different drivers

**Comment by kimchiandgogi** [comment]
> [#527 (comment)](https://github.com/ma1co/Sony-PMCA-RE/issues/527#issuecomment-2211825668)
> 
> This user solved on a a7r4 with different drivers

This fixed it. Thanks!
