### ISSUE TITLE
Not able to change Language in Sony ZV E10 mark 2

### ISSUE THREAD

**Issue by Vhappy86** [ma1co/Sony-PMCA-RE#546]
Sony ZV E10 mark 2 is recently launched, it's not available in list (sported device).
How ever I tried to change with same steps, but facing issue, steps I followed in below sequence.
Step1:-  install zadia.exe in laptop.
Step2:- connect camera and select libusb-win32 and clicked Replace Driver. (Installation completed in 2-3 minutes) And show installation completion message
Step3:-  open pmca-console and then tweaking (updater mode).
It shows error (libusb-win32 driver not installed use zadia to install libusb-win32 driver)

Can anyone help how to resolve or need to do any additional set for Sony ZV E10 mark 2

Thanks in advance for your support.

**Comment by Vhappy86** [comment]
Finally after trying many times it works.
After reading all issues and their answers I tried and it works.
It works in ZV E-10 Mark2 (Launched on 2nd Aug 24 in japan).
Thanks to all who are providing solution, without their efforts and research it was not possible

**Comment by Tvshn11** [comment]
Hi. How could you change? Please 🙏

**Comment by Vhappy86** [comment]
From where you bought and which system you use?

**Comment by lazyracket** [comment]
Great to know that ZV E10 ii is supported.
I'll give it a try too. Thanks for sharing!

**Comment by furiador97** [comment]
I bought my Sony ZVE10 M2 in Japan and I still haven't been able to update the language. I use macOS. Could you possibly help me unlock the languages ​​on it?

**Comment by carlsa** [comment]
This process worked for me on a Japanese Sony ZVE10 M2 on Windows:

- Connect camera to computer
- Set camera to MSC mode on the camera display
- Use [Zadig 2.8](https://zadig.akeo.ie/downloads/) to change the driver to libusb-wind32 (v1.2.7.3)
(someone said that 2.9 doesn't work. I didn't try.
- Used [pmca-gui-v0.18-22-ga82f5ba-win.exe](https://app.box.com/s/0u2gyrrtwoeosvghpv902e8cwzk537i3) as mentioned in this issue:
https://github.com/ma1co/Sony-PMCA-RE/issues/429
Note this is not an official release/download source, the issue mentions that the branch that is was built from was deleted.
- Detected camera in pmca-gui (it should show the model, serial etc.) and used service mode tweak.
- It failed with an error about that it only works with libusb.
- Change the driver again without unplugging it to change the driver for how it enumerated in service mode too.
- Use pmca-gui again and now it worked. The camera restared and asked me to select language.

If you get python errors about that the USB resource is in used, restart the computer. If you get errors about HTTP it means you need an internet connection.

Note that it did not work from a virtual machine, only if I installed it on a "real" windows installation.

**Comment by GangotriEBS** [comment]
Please make youtube tutorial about this as many people are having difficulty.
After the error, How did you change the driver again?
