### ISSUE TITLE
Binary was built for Mac OS X 10.12

### ISSUE THREAD

**Issue by Deph0** [ma1co/Sony-PMCA-RE#55]
Why are released python binaries only for a certain version of macOS?

I'm running a older version of the macbooks, and were trying to install the gui version and console, rather than using the website- as recommended.
```
$ ./pmca-console-v0.15-osx 
[13739] Error loading Python lib '/var/folders/v6/7lz2nxss2q3f71cb0sv5s4k80000gn/T/_MEI49URaD/Python': dlopen: dlopen(/var/folders/v6/7lz2nxss2q3f71cb0sv5s4k80000gn/T/_MEI49URaD/Python, 10): Symbol not found: _clock_getres
  Referenced from: /var/folders/v6/7lz2nxss2q3f71cb0sv5s4k80000gn/T/_MEI49URaD/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/v6/7lz2nxss2q3f71cb0sv5s4k80000gn/T/_MEI49URaD/Python
```
```
$ ./pmca-console-v0.15-osx 
[13824] Error loading Python lib '/var/folders/v6/7lz2nxss2q3f71cb0sv5s4k80000gn/T/_MEIPprKjR/Python': dlopen: dlopen(/var/folders/v6/7lz2nxss2q3f71cb0sv5s4k80000gn/T/_MEIPprKjR/Python, 10): Symbol not found: _clock_getres
  Referenced from: /var/folders/v6/7lz2nxss2q3f71cb0sv5s4k80000gn/T/_MEIPprKjR/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/v6/7lz2nxss2q3f71cb0sv5s4k80000gn/T/_MEIPprKjR/Python
```

**Comment by ma1co** [comment]
The os x builds are built automatically using Travis CI. They are compatible with whatever os x version the Travis CI image is running. Currently, this is 10.12. I could try to downgrade to an older image. Would os x 10.11 compatibility help you?

**Comment by Deph0** [comment]
I would argue that setting a minimum version to what is available would include most people running the release builds, just like on android. In this case, it seems to be 10.10 according to [the travis docs](https://docs.travis-ci.com/user/reference/osx/#OS-X-Version).

**Comment by ma1co** [comment]
@Deph0 Does v0.16 work for you?

**Comment by Deph0** [comment]
Yes, v0.16 works for me.

**Comment by ma1co** [comment]
Thanks for reporting.
