### ISSUE TITLE
X3000 cannot install apps, tweak

### ISSUE THREAD

**Issue by whoever42** [ma1co/Sony-PMCA-RE#60]
attempts to install apps fail with exception:
```
Sony Camcorder is a camera in mass storage mode
Switching to app install mode
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0
```

Info command works, Wifi command does not return any data (neither in hotspot mode nor configured multicamera mode)
Updatershell-shell works and lands me into bootloader linux, as well as pull command
Tried to remove protected mode (to enable telnet and adb, right?), but it didn't seem to have any effect - telnet and adb ports are closed (although, maybe I need OpenMemories-Tweak installed for adb).
Tweak does remember last options saved even after camera has been restarted.

**Comment by whoever42** [comment]
bk w 01640001 01 seems to have helped partially - the camera will switch to App install mode, the camera screen changes to Appli (or similar, that's about all the small screen can handle)
pmca-console scripts reports successful installation of OpenMemories-Tweak-release-0.11.apk, however, I'm not sure if it actually managed to install

still can't get telnet or adb working
from updatershell - no signs of OpenMemories.apk on /dev/dnflasha16/app/ either and if I try to make any changes on that filesystem myself (like build.prop file), they revert back to original version within a few seconds

**Comment by whoever42** [comment]
Found OpenMemories-tweak on /dev/nflasha16/app/ (while original apps are on /dev/**d**nlasha16/app/) as well as other app's I installed via console script in interactive mode like PMCADemo. However, no new icons on the main menu, to launch any of these apps (or any new files on SD card). 

The only thing that changed - something that looks like "charging via usb - on/off" icon in settings menu. Don't know what caused that to appear. Still no luck in obtaining telnet or adb shell.

**Comment by mungewell** [comment]
I'm not an Android coder so the work over the last few days has made my head hurt... that said I'm slowly getting to know the system.

It seems that 'telnet' functionality is defined here:
https://github.com/ma1co/OpenMemories-Tweak/blob/de95322851d8d5626b3af9c41e4db91e43b7babb/app/src/main/java/com/github/ma1co/openmemories/tweak/DeveloperActivity.java#L75

There does not seem to be an 'enable by default' capability, ie. start up telnet the moment tweak is run. Combine that with the hackery to get 'tweak' to auto-run on QX1 described here:
https://github.com/ma1co/OpenMemories-Tweak/issues/58

The other thing that might be causing a problem is that tweak appears to be controlling the WiFi outside the scope of the Sony 'Backup.bin' keys, instead it just uses Androids calls. Might not be a problem, just saying...

**Comment by mungewell** [comment]
BTW this file might give an indication that Tweak has actually been run...
`public static final File LOG_FILE = new File("/sdcard/TWEAKLOG.TXT");`

**Comment by Novex** [comment]
@whoever42 how did you manage to mount `/dev/nflasha16`? Everything I've tried has been met with 
```
mount: mounting /dev/nflasha16 on /mnt failed: Invalid argument

**Comment by ma1co** [comment]
Please install the [launcher app](https://github.com/ma1co/OpenMemories-Launcher), it will replace the integrated live streaming application. You will be able to launch the tweak app from there.
