### ISSUE TITLE
Problem with initializing

### ISSUE THREAD

**Issue by Magnet8** [ma1co/Sony-PMCA-RE#62]
Everytime I initialize the A7RII with the installed Open Memories Tweak App it won't start up again. Need to plug in the USB-Cable and go through Chinese menus. Any idea how I can get this solved? 

I just want to get back to the very basic menu settings where you can dial in time, location and so on...  (Like if you start the camera for the very first time)

**Comment by Magnet8** [comment]
Also with the Open Memories Tweak App deinstalled it won't correctly initialize...

**Comment by ma1co** [comment]
@Magnet8 Before you uninstall the app, please set all settings back to the default value (especially the protection setting).
