### ISSUE TITLE
In app camera support? 

### ISSUE THREAD

**Issue by Giki100** [ma1co/Sony-PMCA-RE#7]
This isn't directly related to the installer I'm just curious if anyone has gotten an actually in app camera to work.  Like snapchat.

**Comment by ma1co** [comment]
The in app camera should work in theory, at least the preview. Apps are likely to crash when taking a picture since Sony made some modifications to the api there.

Try [PMCADemo](https://github.com/ma1co/PMCADemo)'s CameraActivity, that's probably what you want.
