### ISSUE TITLE
DSC-XXX instead of DSC-HX90?!

### ISSUE THREAD

**Issue by yesnoj** [ma1co/Sony-PMCA-RE#75]
Hi Guys, i've an issue with the camera...in version info i found DSC-XXX instead of DSC-HX90, i've another HX90 and had the DUMP.DAT of it, can i upload this to "flash" the other camera as an HX90?
I've changed the mother board to restore the camera, but now the software not recognize the right model and i can't install apps from PlayMemoriesApps becose is not recognized as a camera...how can i solve?

**Comment by mungewell** [comment]
The model name is stored as ASCII in key '0x003e0005' (at least on the A5000) and can be changed via telnet (after installing 'tweak').
```
$ telnet 192.168.1.102
Trying 192.168.1.102...
Connected to 192.168.1.102.
Escape character is '^]'.

BusyBox v1.13.4 (2012-07-17 15:11:04 JST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

/ # bk.elf r 0x003e0005
id:003e0005 size:16 data:
49,4C,43,45,2D,35,30,30,30,00,00,00,00,00,00,00,
/ # bk.elf w 0x003e0005 49 4C 43 45 2D 35 30 30 31
id:003e0005 size:16 data:49, 4C, 43, 45, 2D, 35, 30, 30, 31, 00, 00, 00, 00, 00, 00, 00, 
/ # bk.elf r 0x003e0005
id:003e0005 size:16 data:
49,4C,43,45,2D,35,30,30,31,00,00,00,00,00,00,00
```

**Comment by yesnoj** [comment]
Thanks a lot man!I try this solution! ^_^
To bypass the issue, i've extracted the .apk of the remote control app from my other camera and installed via adb in the other...
I let you know if i solve!

**Comment by yesnoj** [comment]
Update:
It works, but when i restart the camera, come back to the previous DSC-XXX...don't know why :(

**Comment by ma1co** [comment]
The firmware version is stored on the settings partition (_nflasha2_) in the _updater/dat4_ file.
