### ISSUE TITLE
A7R II won't turn on...

### ISSUE THREAD

**Issue by nikdek69** [ma1co/Sony-PMCA-RE#78]
just received a brand new A7R II, applied the latest pmca-gui-v0.16-win, but after restart the camera won't turn on.
The tweak appears to be successfully applied (according from the message displayed from the app), but when trying to turn on the camera the rear screen flashes, it just flashes, and nothing else.
If I try to reconnect the camera with the micro usb cable, it's recognized by the app, and the messages on the screen are "normal", but without the cable, the camera is dead

BTW the first time I tried to turn it on without any issue

suggestions ?

Do I have to apply some sort of reset ?
:(

**Comment by nikdek69** [comment]
Update, with the Micro USB cable connected the camera turns on .. but ONLY with the cable ..., if I remove the cable, the camera / screen won't turn on...

**Comment by redleo2007** [comment]
I have the same problem

**Comment by Bostwickenator** [comment]
I presume you pulled the battery and left the device to sit for a few
minutes and then booted it again?

**Comment by redleo2007** [comment]
Yes, I pulled out the battery after installing the program.

**Comment by ma1co** [comment]
I need some more information. What have you done exactly in pmca-gui? Did you just install apps? Or did you use the "Tweak" tab?

Did you factory reset the camera? This is known to cause issues in some cases, but there are ways to fix this.

**Comment by redleo2007** [comment]
I have installed the program Open Memories: Tweak. After unlock settings menu, chose additional languages (I need Russian language). After that chose the language, turned off the camera, pulled out the battery, put the battery on, turned on the camera and it does not turn on without joining the USB. If you return the initial settings in Tweak, the camera turns on normally. This error occurs IN 7rm2 with firmware 4.00.

**Comment by nikdek69** [comment]
I confirm what redleo2007 said, I did the same, 
and I did it on others camers without this issue

**Comment by ma1co** [comment]
The solution for the initial issue has been posted in #108. For the error when selecting the Russian language, please continue the discussion in #118.
