### ISSUE TITLE
a6300 firmware 2.01

### ISSUE THREAD

**Issue by danico74** [ma1co/Sony-PMCA-RE#79]
Hello. The new firmware version available on the official sony site. Does anyone set unlimited video on this version using pmca?

**Comment by Tr0NiX** [comment]
Hi, tweaks are working on new update ? and do you factory reset camera before update ? .. because i want update camera but i have installed tweaks .. thanks

**Comment by danico74** [comment]
I don't know 2.01 working or not with tweaks. 2.00 was installed on my camera and I not update it to 2.01.

**Comment by Tr0NiX** [comment]
if you find news about 2.01 firmware and tweaks enabled please send pm .. thanks :)

**Comment by DjMasterMario** [comment]
Works perfect on 2.01 firmware (Sony a6300)!

**Comment by tr0nix123** [comment]
Nice! thanks for sharing nice information !.. but i have question did u update from 2.00 to 2.01 without removing tweaks ? ..

**Comment by DjMasterMario** [comment]
I was on 1.01, installed tweaks, updated straight to 2.01. Nothing was removed. =)

**Comment by tr0nix123** [comment]
alright thanks . i will update and post result :) ..

**Comment by bbednarek** [comment]
Can someone confirm that there is an option to install tweaks on version 2.01 directly?

I'm in Japan right now and Sony a6300 is available with version 2.01 only and I'm not sure if I'd be able to enable English language.
