### ISSUE TITLE
Site not working anymore

### ISSUE THREAD

**Issue by Boldbrew** [ma1co/Sony-PMCA-RE#8]
https://sony-pmca.appspot.com/

Error: Not Found

The requested URL / was not found on this server.

**Comment by ma1co** [comment]
> Project sony-pmca is in violation of Google’s Terms of Service. Google has found activity on sony-pmca (sony-pmca) that appears to be hosting content that appears to be phishing.

So it seems that Google isn't happy with what we're doing. I submitted an appeal and I'm currently waiting for their answer.

In the meantime, use the local installer instead:
`pmca install -s "" -f app.apk`

**Comment by kiphoenix** [comment]
Hi bro,

Can you show me how to use local pc to active all languague on my nex 6 japan?
How can i use "pcma" keyword?

Thank you very much!!!

**Comment by ma1co** [comment]
Download the pmca executable from the releases (this repo), download the apk from the Tweak repo und run the above command.

**Comment by Boldbrew** [comment]
// In the meantime, use the local installer instead:
// pmca install -s "" -f app.apk
Not working for me 
Querying MTP device
Sony Corporation NEX-6 is a camera in app install mode
Uploading apk
Traceback (most recent call last):
  File "<string>", line 172, in <module>
  File "<string>", line 166, in main
  File "<string>", line 105, in installCommand
  File "<string>", line 41, in installApp
  File "pmca\marketserver\server.py", line 103, in run
  File "site-packages\requests\models.py", line 808, in json
  File "json\__init__.py", line 339, in loads
  File "json\decoder.py", line 364, in decode
  File "json\decoder.py", line 382, in raw_decode
ValueError: No JSON object could be decoded
pmca returned -1

C:\Windows\system32>"D:\Projects\Alpha FW\Wave3\pmca-v0.4-win.exe" market
Please enter your Sony Entertainment Network credentials

Email: Traceback (most recent call last):
  File "<string>", line 172, in <module>

pmca returned -1

**Comment by ma1co** [comment]
Did you run it with the -s option? You have to provide an empty string, otherwise it will try to connect to app engine.

**Comment by ma1co** [comment]
It's back online.

> Good news! Based on either additional information you provided or further analysis we performed, we determined that your Google Cloud Platform / API Project is fully in compliance with our policies at the current time.

**Comment by JoshWobbles** [comment]
Neither the site nor this method seem to be working

**Comment by hohaha045** [comment]
Sorry reply on old issue, but is the website (https://sony-pmca.appspot.com) down? I can install it using the local installer but is there anywhere I could get other apps? @ma1co
