### ISSUE TITLE
Issues tweaking a DSC-RX100

### ISSUE THREAD

**Issue by osheroff** [ma1co/Sony-PMCA-RE#80]
I have this camera:

```
Sony Corporation DSC-RX100 is a camera in MTP mode

Model:              DSC-RX100
Product code:       0080812834
Serial number:      06620348
Firmware version:   1.10
```

When I go to do tweaks, this happens:

1. The camera puts up a menu that says "Resets camera." with a single "OK" button.
2. I click ok.
3. The power led on the camera blinks once and then goes solid green. 
4. Nothing else happens.  The firmware update times out.  The camera is unresponsive and basically dead until I pull the battery and put it back in.

Anyone see anything like this before?

**Comment by ma1co** [comment]
@osheroff 
What operating system are you using? You seem to have issues with the USB mass storage drivers. Can you try switching the camera to mass storage mode? Does it connect? If this doesn't work, firmware updates won't work, either.

The camera seems to behave correctly (in firmware update mode, it appears to be "dead", however it should connect to your computer in mass storage mode).

**Comment by osheroff** [comment]
thanks for the uber-quick response.  I'm on OSX, couldn't get the camera recognized in mass-storage mode, so I switched it over to MTP, which got it recognized, but now that. 

I wanted to avoid installing those dubious sony drivers, but I guess if that's the way i gotta do it I will. thanks!  Will update with further info

**Comment by osheroff** [comment]
What do you mean exactly by "Does it connect?"  The Finder mounts `PMHOME`, but with or without the sony drivers and browser plugin, pcma-gui can't find the camera when it's in mass-storage mode. 

btw, high sierra 10.13.13

**Comment by ma1co** [comment]
Apparently, there are still some issues on high sierra...

Sorry, by "does it connect", I meant: Does pmca-gui find the device when you run the "get camera info" command?

Can you post the output of `kextstat | grep sony` when the camera is connected?

**Comment by osheroff** [comment]
```
alpha21:~/src/maxwell (ben/bootstrap_task) $ kextstat | grep sony
alpha21:~/src/maxwell (ben/bootstrap_task) $
```

nothin'.

**Comment by ma1co** [comment]
Just to recap:
* You installed the [PMCADownloader](https://sony-pmca.appspot.com/plugin/install) browser plugin? And allowed the installation of the kernel extension?
* The camera is connected in mass storage mode?
* And nothing shows up in kextstat?

Can you maybe try their [DriverLoader](https://support.d-imaging.sony.co.jp/mac/driver/1013/en/) app? It isn't supported in pmca-gui 0.16, but the kernel extension should show up in kextstat...

**Comment by osheroff** [comment]
Ok, here's the latest:

- Did a manual `sudo kextload -bundle-id com.sony.driver.dsccamDeviceInfo00`.  This got me to another "blocked Sony software" in security/privacy, whitelisted the extension and restarted.
- Now pmca-gui.py can see the camera in mass-storage mode, but:
- "start tweaking" throws "OpenUserClient failed"

**Comment by osheroff** [comment]
https://www.dropbox.com/s/iud6yvxyupnze23/Screenshot%202018-02-08%2014.57.21.png?dl=0

**Comment by osheroff** [comment]
<img width="782" alt="screenshot 2018-02-08 14 57 21" src="https://user-images.githubusercontent.com/260084/36002856-8a846b68-0ce0-11e8-80e8-17ce3cb335b3.png">

**Comment by ma1co** [comment]
Well, that's some progress... Weird that you get the OpenUserClient error only for the updatershell command and not the info command. Just to make sure, your camera is in normal mode, not firmware update mode when you get the sense error?

I just retried everything in my virtualbox os x installation and everything works fine...

**Comment by osheroff** [comment]
Yeah it’s just in mass storage mode

**Comment by ma1co** [comment]
The whole kernel module situation is a big mess. We'd need a dedicated OS X developer having a look at this...

You can always try to fall back to libusb drivers by running the following command: `pmca-console updatershell -d libusb` (sorry, terminal only)
Afaik, you have to run this as superuser however. Which is totally ok if you don't want to.

**Comment by osheroff** [comment]
libusb failed too.  I gave up and got it (seemingly) working via virtualbox.  I dunno what you wanna do with this issue, up to you.
