### ISSUE TITLE
Can't Log in on camera And Trying to configure using C.DAT

### ISSUE THREAD

**Issue by MikeTHEPro** [ma1co/Sony-PMCA-RE#81]
So I have a HX-400V and I have installed the app but i can't click on textboxes to put my email or pass. And after a while I found a file in my SD Card called "C.DAT" in the following directory "D:\PRIVATE\STG\". I opened this file on Notepad++ and found this line "`{"credentials":{}}`" and I was wondering if I could put my credentials there. If yes tell me in what form should I enter them. Could it be something like this "`{"credentials":{"example@gmail.com", "password"}`}". Please tell me the correct syntax, just to see if it will work. Thanks, Keep up the good work.

P.S if you need more info let me know by contacting me on mixalisselgall@gmail.com , or Reply here.

**Comment by ma1co** [comment]
Please report this in the [correct repository](https://github.com/Bostwickenator/STGUploader). Thanks.
