### ISSUE TITLE
RX0 firmware 2.0 can not apply tweaks

### ISSUE THREAD

**Issue by yundin2000** [ma1co/Sony-PMCA-RE#82]
`Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Model:              DSC-RX0
Product code:       0002447701
Serial number:      03010004
Firmware version:   2.00

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Using firmware for model DSC-RX0

Unknown device: DSC-RX0

`
same on MTP

**Comment by ma1co** [comment]
The RX0 is only supported in the latest development builds. You can download them [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). Please let us know what works.

**Comment by yundin2000** [comment]
Solved! Like a charm! Thank you! everythink works

**Comment by ma1co** [comment]
Thanks for reporting!
