### ISSUE TITLE
App Installation gets stuck 

### ISSUE THREAD

**Issue by TimetravelerDD** [ma1co/Sony-PMCA-RE#85]
I can't install any apps. It worked before. Now I always get stuck after:

```
Switching to app install mode
Waiting for camera to switch...
Downloading apk
Starting task
Starting communication
Uploading 0%
```

I can wait for ever but nothing happens. Only solution is to unplug.

The console says: 

```
Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to app install mode
Waiting for camera to switch...
Downloading apk
Starting task
Starting communication
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 91, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 69, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 256, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 74, in installApp
  File "C:\projects\sony-pmca-re\pmca\installer\__init__.py", line 84, in install
ConnectionRefusedError: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
[63024] Failed to execute script pmca-console
```

Win 10
Sony A6000
FW 3.20 and FW 2.0

I tried v 0.16, 0.15 both gui and console multiple times with different apps.
Getting camera info works fine btw.

**Comment by ma1co** [comment]
pmca-gui starts a webserver on port 4443 and tries to connect to https://127.0.0.1:4443/ . Maybe your firewall is blocking the request? Can you try to (temporarily) disable your firewall?

**Comment by TimetravelerDD** [comment]
Hi,
It works now! Thank you so much!
Not sure why though: I deactivated the Windows FW, tried it, and it worked instantly. Then I enabled it again and it's still working. Maybe a reboot was all I needed - Sorry for this silly mistake.

Cheers,  Markus
