### ISSUE TITLE
A6300 time limit tweak not working with firmware 2.01

### ISSUE THREAD

**Issue by Vertigo007** [ma1co/Sony-PMCA-RE#87]
Hi,

I've try many different way to get this tweak  working on my A6300 2.01 and I can,t make it happen.
ma1co can you do anything about this so it would work?

Thanks

**Comment by lapol** [comment]
It works fine on my A6300 with 2.01. Wasn’t doing anything more. It just works.

**Comment by bbednarek** [comment]
@lapol Did you install it on a6300 with firmware version 2.01 and it worked out?

**Comment by lapol** [comment]
Yes, I have brand new camera with 2.01 firmware and it works. If You have connection issues (I couldn't make the software work on my Mac) just try PC with latest Windows 10.

**Comment by bbednarek** [comment]
I managed to make it work on the brand Sony a6300 camera bought in Japan with firmware version `2.00`. I had some issues with installing it on `Mac Os High Sierra 10.13.6` like:
* `Error: Network connection` https://github.com/ma1co/Sony-PMCA-RE/issues/33
* `usb.core.USBError Erno13 Acess denied (insufficient permissions)` https://github.com/ma1co/Sony-PMCA-RE/issues/102, https://github.com/ma1co/Sony-PMCA-RE/issues/6

but I solved it by:
* setting `USB Connection` to `Mass Storage` (`マスストレージ`) in Japanese 
* installing [pmca-gui-v0.17-osx.dmg](https://github.com/ma1co/Sony-PMCA-RE/releases/tag/v0.17) 
* installing [PlayMemories Camera Apps Downloader for Mac](https://sony-pmca.appspot.com/plugin/install)
* installing [DriverLoader_1013](https://support.d-imaging.sony.co.jp/mac/driver/1013/en/)
* running `DriverLoader_1013` and then using `pmca-gui-v0.17-osx.dmg`

All worked perfectly. Thank you very much @ma1co and @lapol

**Comment by lapol** [comment]
Can You check if the timelapse app and silent shutter option works fine at Your A6300? I struggle to make it work.

**Comment by bbednarek** [comment]
@lapol yes it works for me, but it's possible to set it up in *Manual* mode only. Steps:
* Switch to *M*
* Menu
* Steering wheel
* Silent Shooting -> switch to *on*

**Comment by lapol** [comment]
Timelapse app works like charm. 
I have just reinstalled it and silent mode finally works. Thank You for support.

PS: I'm from Poland too :)
