### ISSUE TITLE
sony a7m3 Unknown device

### ISSUE THREAD

**Issue by bob198313** [ma1co/Sony-PMCA-RE#88]
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-7M3 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 74, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 239, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 35, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006

Querying MTP device
Sony Corporation ILCE-7M3 is a camera in MTP mode

Getting device info
Using firmware for model ILCE-7M3

Unknown device: ILCE-7M3

**Comment by EldarAron** [comment]
Will there be support for the A7 M3?

**Comment by ma1co** [comment]
The A7M3 does not support android apps anymore. Additionaly, it has a new firmware format and we don't know the encryption keys. So currently we have no way inside those cameras. I am not aware of any way to dump those keys in the near future. So no, the A7M3 is not supported.

**Comment by wanghaixian** [comment]
👨🏻‍💻Sony camera adds English menu
💰Alipay   PayPal Usdt Dogecoin
🔰100% success.  There is no risk.  The authorization scheme from the factory is not a third-party cracking program.  You can reset the camera, upgrade the firmware, the language will not disappear
📝WhatsApp:  +79055473456 
📧Email:wanghaixian1995@gmail.com 

📷A1(α1) 80$   
🎥FX3 65$
📷A9——A9M2 65$
📷A7——A7M4 65$
📷A7R——A7R4 65$
📷A7R3A——A7R4A 65$
📷A7S——A7S3 65$
📷A7C 65$
📷RX1RM2 65$
📷A6000——A6600  50$
📷RX100——RX100M7 50$
📷ZV1——ZV-E10 50$

⚠️ a1 A7s3 A7m4 fx3 These models are new menus and do not support Japanese cameras 🇯🇵🙅🏻.  Support cameras from China or other countries✅

✅A7M3 A9M2 A7R3 A7R4 A7C A6xx ZVxx.......All cameras that use the old menu, support Japan and China, including all other countries and regions


💻Remotely, you need to prepare:
 computer (Windows✅ Macos❎)
 USB cable
 high speed internet
 (Remotely, you have to pay in advance)

⬇️⬇️You can also add other languages⬇️⬇️
日本語🇯🇵   English🇺🇸   Français🇫🇷   Deutsch🇩🇪
Español🇪🇸   Italiano🇮🇹   Português🇵🇹   简体中文🇨🇳
繁體中文🇭🇰   العربية🇸🇦   한국어🇰🇷  Nederlands🇳🇱 Русский🇷🇺   ภาษา ไทย🇹🇭   فارسی🇮🇷   Magyar🇭🇺
Česky🇨🇿   Polski🇵🇱   Svenska🇸🇪   Norsk🇳🇴 
Türkçe🇹🇷   Ελληνικά🇬🇷   Română🇷🇴 
Bahasa Melayu🇲🇾   Indonesia🇵🇱   Suomi🇫🇮 
hrvatski🇭🇷   Dansk🇩🇰   Български🇧🇬 
Tiếng Việt🇻🇳  Українська🇺🇦   Português (Brasil)🇧🇷
France(Canada) Язык🇨🇦
———————————————————————————
👨🏻‍💻If your camera is a very old model, you can add languages ​​through a third-party cracker, it is free 👉🏻 https://github.com/ma1co/OpenMemories-Framework/blob/master/docs/Cameras.md
