### ISSUE TITLE
A7r3 support?

### ISSUE THREAD

**Issue by kmoreau893** [ma1co/Sony-PMCA-RE#89]
I have this installed on my A7rii and A7sii - works great for removing 30min limit - Does this work on A7r3?

**Comment by ma1co** [comment]
The A7RM3 has a new firmware format and we don't know the encryption keys. So currently we have no way inside those cameras. I am not aware of any way to dump those keys in the near future. So no, the A7RM3 is not supported.

**Comment by solomatovroman** [comment]
Is there any news regarding A7RM3? Would be nice to unlock languages.
