### ISSUE TITLE
Exception: Response code not OK: 0xa489

### ISSUE THREAD

**Issue by mx4k** [ma1co/Sony-PMCA-RE#9]
I get this error verytime I try to install an APK file which was downloaded with this tool.

> D:\Downloads>pmca-v0.4-win.exe install -f SmartRemote420.apk
> Using Windows drivers
> Looking for Sony devices
> 
> Querying MTP device
> Sony Corporation ILCE-6000 is a camera in app install mode
> Uploading apk
> Starting communication
> Uploading 0%
> Uploading 100%
> Downloading 4%
> Traceback (most recent call last):
>   File "<string>", line 172, in <module>
>   File "<string>", line 166, in main
>   File "<string>", line 105, in installCommand
>   File "<string>", line 46, in installApp
>   File "pmca\installer\__init__.py", line 69, in install
>   File "pmca\usb\sony.py", line 271, in sendSslData
>   File "pmca\usb\sony.py", line 250, in _sendCommand
>   File "pmca\usb\sony.py", line 204, in _write
>   File "pmca\usb\__init__.py", line 58, in _checkResponse
> Exception: Response code not OK: 0xa489
> pmca returned -1

Edit: I tried this tool now on several computers and it is always the same error with my camera. But installing using a local server (-s "") is working fine.

**Comment by lullibi** [comment]
have a look here:
https://github.com/ma1co/Sony-PMCA-RE/issues/15
try masstorage mode..
