### ISSUE TITLE
Sony a6300 issue: error downloading DLLs

### ISSUE THREAD

**Issue by Luca1996O** [ma1co/Sony-PMCA-RE#92]
Hi!
I'm trying to use your pmca-gui with my Sony a6300, but it doesn't work at all. I can't even get camera info. It displays:
![immagine](https://user-images.githubusercontent.com/38019761/38219794-984d708e-36d7-11e8-95a1-bca540105d38.png)
The same if I change USB cable, the same either I put my camera on MTP or Auto. I think it's a DLL error, but I got no idea...
Thank you.

**Comment by Luca1996O** [comment]
I'm using Windows 10 (Professional). I've got the same issue on another laptop Windows 10 Home as well.

**Comment by ma1co** [comment]
Is it the N version (without media player)?

**Comment by Luca1996O** [comment]
Yes, they both are. Does the software need Windows softwares as Media Player?

**Comment by ma1co** [comment]
Apparently you need the Media Feature Pack to communicate with MTP devices...
Does the Sony browser plugin work?

**Comment by Luca1996O** [comment]
Ok, thank you. I'm gonna try with the standard Windows 10 Pro so! 👍 
Neither that :(
