### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by yrast** [ma1co/Sony-PMCA-RE#96]
pcma-gui v0.17 on OS X 10.13 and a A7Sii, but I keep getting “No devices found. Ensure your camera is connected.”

Searching through the issues I found I should `brew install libusb` (seemed to install fine; that led to a huge brew update...). Same problem. Then I found the “DriverLoader_1013” (seemed to go fine), but still have the same problem.

I tried MTP and Mass Storage mode, no luck.

And that's when I decided to seek help here (cause I'm out of ideas).

<img width="390" alt="screen shot 2018-05-09 at 12 22 13 pm" src="https://user-images.githubusercontent.com/715637/39826742-a91ecba6-5383-11e8-91a8-eb77aeba83b6.png">

**Comment by marekkaczkowski** [comment]
Same on macOS 10.13.6 Beta (17G62a) + Sony A7S (mark I)

**Comment by AldeRoberge** [comment]
Dude, I had the same problem. Chromecast Micro USB cable... Thank god you posted the answer.
