### ISSUE TITLE
A7 iii support?

### ISSUE THREAD

**Issue by Tiiti** [ma1co/Sony-PMCA-RE#97]
Heya,

I am super keen to buy the a7iii to replace my A6300 but I worried the 30min record limit will become a major issue for me as someone who does a lot of video that goes well into the 2-3hr mark of continuous shooting.  

Is there any hope this may eventually be hacked?  It seems unlikely now Sony have remove play memories so losing a way into the system?

Many thanks.

**Comment by Bostwickenator** [comment]
Dupe, please see #89. Close this if you can.

**Comment by Zhorz** [comment]
Да походу не получится в ближайшее время отключить 30 минутный предел,где только не был пока вопрос открыт.

**Comment by ma1co** [comment]
The A7M3 is currently unsupported. Please monitor the issues for [fwtool](https://github.com/ma1co/fwtool.py).

**Comment by wanghaixian** [comment]
👨🏻‍💻Sony camera adds English menu
💰Alipay   PayPal Usdt Dogecoin
🔰100% success.  There is no risk.  The authorization scheme from the factory is not a third-party cracking program.  You can reset the camera, upgrade the firmware, the language will not disappear
📝WhatsApp:  +79055473456 
📧Email:wanghaixian1995@gmail.com 

📷A1(α1) 80$   
🎥FX3 65$
📷A9——A9M2 65$
📷A7——A7M4 65$
📷A7R——A7R4 65$
📷A7R3A——A7R4A 65$
📷A7S——A7S3 65$
📷A7C 65$
📷RX1RM2 65$
📷A6000——A6600  50$
📷RX100——RX100M7 50$
📷ZV1——ZV-E10 50$

⚠️ a1 A7s3 A7m4 fx3 These models are new menus and do not support Japanese cameras 🇯🇵🙅🏻.  Support cameras from China or other countries✅

✅A7M3 A9M2 A7R3 A7R4 A7C A6xx ZVxx.......All cameras that use the old menu, support Japan and China, including all other countries and regions


💻Remotely, you need to prepare:
 computer (Windows✅ Macos❎)
 USB cable
 high speed internet
 (Remotely, you have to pay in advance)

⬇️⬇️You can also add other languages⬇️⬇️
日本語🇯🇵   English🇺🇸   Français🇫🇷   Deutsch🇩🇪
Español🇪🇸   Italiano🇮🇹   Português🇵🇹   简体中文🇨🇳
繁體中文🇭🇰   العربية🇸🇦   한국어🇰🇷  Nederlands🇳🇱 Русский🇷🇺   ภาษา ไทย🇹🇭   فارسی🇮🇷   Magyar🇭🇺
Česky🇨🇿   Polski🇵🇱   Svenska🇸🇪   Norsk🇳🇴 
Türkçe🇹🇷   Ελληνικά🇬🇷   Română🇷🇴 
Bahasa Melayu🇲🇾   Indonesia🇵🇱   Suomi🇫🇮 
hrvatski🇭🇷   Dansk🇩🇰   Български🇧🇬 
Tiếng Việt🇻🇳  Українська🇺🇦   Português (Brasil)🇧🇷
France(Canada) Язык🇨🇦
———————————————————————————
👨🏻‍💻If your camera is a very old model, you can add languages ​​through a third-party cracker, it is free 👉🏻 https://github.com/ma1co/OpenMemories-Framework/blob/master/docs/Cameras.md
