### ISSUE TITLE
NEX-5 support

### ISSUE THREAD

**Issue by polardegausser** [ma1co/Sony-PMCA-RE#98]
Greetings,

I wonder has there been any progress in gen1 cameras. I own NEX-5 and I'm willing to provide my time to figure out the linux subsystem and get to the settings. I have motivation because I'd really like to disable the rec display on HDMI output and sleep timeout to use the camera for live shows. I already have a dump of nflasha and bootloader which I can provide, as well as last firmware unpacked.

**Comment by polardegausser** [comment]
Also, if there is need, I can do some poking around in IDA, at least with elfs in /usr/bin

**Comment by jeanthom** [comment]
Hi,

I'm going to do some work on my NEX-3. I'd like to try enabling 1080p recording or at least tweaking video profiles, but clean HDMI output could be cool.

For the moment being, I have some Sony executables loaded in IDA. I may have some ideas on how to implement clean HDMI.

Drop me an email at nex@jeanthomas.me

**Comment by thegallivanter** [comment]
Hi Jean Thomas, 

I`m also trying to work on my nex-3. Trying to find out how to use the pmca-console to find and change certain settings. Mungewell shows the 'bk.elf r' and 'bk.elf w' commands [here](https://github.com/ma1co/Sony-PMCA-RE/issues/67#issuecomment-352959615).

He points at the id '0x003e0005' to be the 'model name' and the value '49 4C 43 45 2D 35 30 30 31' to be the model a5001. But how do people know what id stands for what setting, and what value means what exactly? 

Which ID stands for the enabled recording modes for example? And which value allows 1080p recording in other cameras?

**Comment by jeanthom** [comment]
The value is an ASCII string encoded in hexadecimal : 49,4C,43,45,2D,35,30,30,30 is "ILCE-5000".

I don't think we can get 1080p recording simply by editing a value because the code seems to differ between the NEX-3 and the NEX-5, perhaps we should try flashing a NEX-5 firmware on a NEX-3 ?

**Comment by thegallivanter** [comment]
This issue has a useful discussion:
https://github.com/ma1co/fwtool.py/issues/6

**Comment by jeanthom** [comment]
I opened this repository so we could speak about non-PCMA cameras : https://github.com/jeanthom/NEX1stGenRE
